name: red_edge_app
description: RED EDGE Installation Management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.0

  # Local Storage
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.3

  # Networking
  dio: ^5.4.3
  dio_smart_retry: ^6.0.0
  connectivity_plus: ^6.0.3

  # Camera & Media
  camera: ^0.11.0
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_image_compress: ^2.3.0

  # UI
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1

  # Utilities
  uuid: ^4.4.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  fpdart: ^1.1.0
  get_it: ^8.0.0
  geocoding: ^3.0.0

  # PDF
  pdf: ^3.11.1
  printing: ^5.13.3

  # Code Generation Annotations
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  mockito: ^5.4.4
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - assets/icons/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/red_edge_app_logo.jpg" # Aapki file ka path
  adaptive_icon_background: "#FFFFFF" # Android ke liye background color (Green ke sath white accha lagega)
  adaptive_icon_foreground: "assets/images/red_edge_app_logo.jpg"  