import 'package:hive_flutter/hive_flutter.dart';

class HiveService {
  static const String jobsBox = 'jobs';
  static const String stepsBox = 'steps';
  static const String photosBox = 'photos';
  static const String syncQueueBox = 'sync_queue';
  static const String authBox = 'auth';
  static const String settingsBox = 'settings';

  static Future<void> init() async {
    await Hive.initFlutter();

    // Register adapters — generated by hive_generator
    // Hive.registerAdapter(JobModelAdapter());
    // Hive.registerAdapter(StepModelAdapter());
    // Hive.registerAdapter(PhotoModelAdapter());
    // Hive.registerAdapter(SyncOperationAdapter());
  }

  static Future<void> openBoxes() async {
    await Future.wait([
      Hive.openBox(jobsBox),
      Hive.openBox(stepsBox),
      Hive.openBox(photosBox),
      Hive.openBox(syncQueueBox),
      Hive.openBox(authBox),
      Hive.openBox(settingsBox),
    ]);
  }

  static Box getBox(String name) => Hive.box(name);

  static Future<void> clearAll() async {
    await Hive.box(jobsBox).clear();
    await Hive.box(stepsBox).clear();
    await Hive.box(photosBox).clear();
    await Hive.box(syncQueueBox).clear();
    await Hive.box(authBox).clear();
  }
}