// import 'package:suprapp/app/features/groceries/models/product_model.dart';

// class ProductRepository {
//   List<Product> getAllDeals() {
//     return [
//       Product(
//         id: '1',
//         title: 'Pure Organic Honey Jar',
//         price: '\$10',
//         discount: '15% OFF',
//         oldPrice: '\$12',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQavcMVvrXn7KoldH8-1IiGNwLbh0mFtskAgA&s',
//       ),
//       Product(
//         id: '2',
//         title: 'Unsweetened Almond Milk Pack',
//         price: '\$6',
//         discount: '10% OFF',
//         oldPrice: '\$7',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrXh06hIlgR0eXl4lKBHgaz9kmS--IkgmHoQ&s',
//       ),
//       Product(
//         id: '3',
//         title: 'Gluten-Free Bread Loaf',
//         price: '\$4',
//         discount: '20% OFF',
//         oldPrice: '\$5',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmKBeNnUHZUqVZ8JYi6ZJt1w3LLud4yNS4Gg&s',
//       ),
//       Product(
//         id: '4',
//         title: 'Extra Virgin Olive Oil Bottle',
//         price: '\$15',
//         discount: '25% OFF',
//         oldPrice: '\$20',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDCVqZJH_9rTJIdCqXD3ocxttyyQxCIlfbww&s',
//       ),
//       Product(
//         id: '5',
//         title: 'Organic Brown Rice 1kg',
//         price: '\$8',
//         discount: '12% OFF',
//         oldPrice: '\$9',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRTyAHH_lq6mZVGjAk1rWnZnLEj9deTCiV2Q&s',
//       ),
//       Product(
//         id: '6',
//         title: 'Natural Peanut Butter',
//         price: '\$5',
//         discount: '15% OFF',
//         oldPrice: '\$6',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrNR84My__uYmm92Izdbkq7kA_2skvbcTJKw&s',
//       ),
//       Product(
//         id: '7',
//         title: 'Quinoa Grain 500g',
//         price: '\$7',
//         discount: '10% OFF',
//         oldPrice: '\$8',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToa1XYXJxJ88nx-CN_7uISowMpt2NHHIm8aA&s',
//       ),
//       Product(
//         id: '8',
//         title: 'Organic Green Tea Box',
//         price: '\$4',
//         discount: '20% OFF',
//         oldPrice: '\$5',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK8UtgPv-AUp8PHG-gC6mDK2IJ98VV5MPJAA&s',
//       ),
//       Product(
//         id: '9',
//         title: 'Almond Butter Spread',
//         price: '\$9',
//         discount: '10% OFF',
//         oldPrice: '\$10',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeLv53AmXM6MqlUTh1jHl9aHr6nb5qSVihHg&s',
//       ),
//       Product(
//         id: '10',
//         title: 'Raw Chia Seeds 250g',
//         price: '\$3',
//         discount: '5% OFF',
//         oldPrice: '\$4',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmoP0LPuNi9YuxHe2OeiD2yX0nZG3UqfBQog&s',
//       ),
//       Product(
//         id: '11',
//         title: 'Natural Coconut Water',
//         price: '\$2',
//         discount: '10% OFF',
//         oldPrice: '\$3',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrkCqF4nYdXW8IMUeNVzdIJ1KM_NK8Y-pmRg&s',
//       ),
//       Product(
//         id: '12',
//         title: 'Organic Rolled Oats',
//         price: '\$5',
//         discount: '15% OFF',
//         oldPrice: '\$6',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1KoQ-rz7jK5MIWwnEiLZLxPR-aUXflpS4xw&s',
//       ),
//       Product(
//         id: '13',
//         title: 'Vegan Protein Bar Pack',
//         price: '\$12',
//         discount: '20% OFF',
//         oldPrice: '\$15',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS01kVSuJdXtTN9zjpjYwZ91BJzZclbe5LuVA&s',
//       ),
//       Product(
//         id: '14',
//         title: 'Organic Flax Seeds',
//         price: '\$3',
//         discount: '10% OFF',
//         oldPrice: '\$4',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTohXfrbpmjD_Kz_zzynJz0gN0K4iZFoVQUOA&s',
//       ),
//       Product(
//         id: '15',
//         title: 'Natural Apple Cider Vinegar',
//         price: '\$6',
//         discount: '12% OFF',
//         oldPrice: '\$7',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpEJDXh78avA8HbtpTbmMCZVfj0WRm0kPaZQ&s',
//       ),
//       Product(
//         id: '16',
//         title: 'Multigrain Cereal Pack',
//         price: '\$4',
//         discount: '8% OFF',
//         oldPrice: '\$5',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZTWvcsovCm4PFe9AY9pnOZ4yR_pN2j3gI2g&s',
//       ),
//       Product(
//         id: '17',
//         title: 'Fresh Organic Carrots',
//         price: '\$2',
//         discount: '5% OFF',
//         oldPrice: '\$3',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmzML3OYfRA-4Pa9n1DrDrG3CihQaZ-MHZpA&s',
//       ),
//       Product(
//         id: '18',
//         title: 'Whole Wheat Pasta 500g',
//         price: '\$3',
//         discount: '10% OFF',
//         oldPrice: '\$4',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu0eToLUAXi_BdORqBKAX-I4s3ZZI5Qa5T2A&s',
//       ),
//       Product(
//         id: '19',
//         title: 'Organic Herbal Shampoo',
//         price: '\$9',
//         discount: '20% OFF',
//         oldPrice: '\$11',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1XeG9xSkslTXWGbOssXtuAGXVOuOJ0UEN-w&s',
//       ),
//       Product(
//         id: '20',
//         title: 'Natural Deodorant Stick',
//         price: '\$7',
//         discount: '15% OFF',
//         oldPrice: '\$8',
//         imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTArJ8HFvqEkBqTHruvW-Zp3MI88JkMHv7glw&s',
//       ),
//       final items = [
//   {
//     'title': 'Sanita Club Biodegradable',
//     'price': 'AED 25.99',
//     'discount': '-9%',
//     'id': 'item_1',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQavcMVvrXn7KoldH8-1IiGNwLbh0mFtskAgA&s',
//   },
//   {
//     'title': 'Sanita Paper Cups 266.16 m...',
//     'price': 'AED 13.85',
//     'discount': '-8%',
//     'id': 'item_2',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrXh06hIlgR0eXl4lKBHgaz9kmS--IkgmHoQ&s',
//   },
//   {
//     'title': 'Sanita Club Garbage Bags',
//     'price': 'AED 19.95',
//     'discount': '-15%',
//     'id': 'item_3',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRib_d0P13XP13Mypnc8tu893qOD9Rl-MdILg&s',
//   },
// ];

// final herbal = [
//   {
//     'title': 'Himalaya Soap Neem & Turm...',
//     'price': 'AED 19.20',
//     'old': 'AED 24',
//     'discount': '-20%',
//     'id': 'herbal_1',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJtZEE5zxcfq-nAlS_5fJxJrlcjlnxLWOPMQ&s',
//   },
//   {
//     'title': 'Himalaya Soap Moisturizing A...',
//     'price': 'AED 19.20',
//     'old': 'AED 24',
//     'discount': '-20%',
//     'id': 'herbal_2',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRunZcCzD4RN1X8jK2u5G9VjfFcGExuA5i4dQ&s',
//   },
//   {
//     'title': 'Himalaya Pure Tulsi & Aloe V...',
//     'price': 'AED 25.90',
//     'old': 'AED 30.45',
//     'discount': '-15%',
//     'id': 'herbal_3',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRx2-LEkNXJNKwlafI9IkC-ZUMcs7OXfptRGw&s',
//   },
// ];

// final beverages = [
//   {
//     'title': 'Pepsi Can 330ml',
//     'price': 'AED 3.50',
//     'old': 'AED 4.00',
//     'discount': '-12%',
//     'id': 'bev_1',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWm8nJlEPObT1-XdlBT7CagggnQ4t7pjGFEQ&s',
//   },
//   {
//     'title': '7Up Bottle 1.5L',
//     'price': 'AED 6.25',
//     'old': 'AED 7.00',
//     'discount': '-11%',
//     'id': 'bev_2',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfnM_O9lNMewzSSjYhS_fDM1ma3vFY4_fo4Q&s',
//   },
//   {
//     'title': 'Red Bull 250ml',
//     'price': 'AED 8.00',
//     'old': 'AED 9.50',
//     'discount': '-16%',
//     'id': 'bev_3',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvqMwbho-a0epWPgUGA-C4Htn7DYJwIEW3oA&s',
//   },
// ];

// final bundleOffers = [
//   {
//     'title': 'Combo Pasta Pack',
//     'price': 'AED 18.00',
//     'old': 'AED 22.00',
//     'discount': '-18%',
//     'id': 'bundle_1',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt4bajQIs2fcjMbvO_qcCiKC2BbDM43CgmSw&s',
//   },
//   {
//     'title': 'Buy 1 Get 1 Biscuits',
//     'price': 'AED 10.00',
//     'old': 'AED 14.00',
//     'discount': '-29%',
//     'id': 'bundle_2',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRinpOFSYKilh42mODD8KwHwILgNCCI9Leq4w&s',
//   },
//   {
//     'title': 'Rice & Lentil Combo',
//     'price': 'AED 30.00',
//     'old': 'AED 35.00',
//     'discount': '-14%',
//     'id': 'bundle_3',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0V_h6HGYxgYPyZa4Rg3QOZRAsIypy2IMi8g&s',
//   },
// ];

// final reducedToClear = [
//   {
//     'title': 'Choco Cookies (Expiring Soon)',
//     'price': 'AED 5.00',
//     'old': 'AED 10.00',
//     'discount': '-50%',
//     'id': 'clear_1',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp8bRiOhsb-UKLtNVe8Kvya31CVmYId2MRCg&s',
//   },
//   {
//     'title': 'Cheddar Cheese 250g',
//     'price': 'AED 12.00',
//     'old': 'AED 18.00',
//     'discount': '-33%',
//     'id': 'clear_2',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwjohTySvtGuzJZEqe9Ax0mSTb8hAyFc-NWQ&s',
//   },
//   {
//     'title': 'Fresh Milk 1L (Expiring Soon)',
//     'price': 'AED 8.00',
//     'old': 'AED 11.00',
//     'discount': '-27%',
//     'id': 'clear_3',
//     'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXJj9n4p_wxU0Wl3uouU1SY5Jvqk5K1nLqhzM&s',
//   },
// ];

//     ];
//   }
// }
