// import 'package:hive/hive.dart';
// import 'features/auth/data/models/user_model.dart';
// import 'features/jobs/data/models/job_model.dart';
// import 'core/sync/sync_operation.dart';

/// This file should be generated by Hive during build_runner
/// However, for completeness, we document the adapter setup here.

/// To generate adapters:
/// 1. Add @HiveType(typeId: X) to your model classes
/// 2. Run: dart run build_runner build --delete-conflicting-outputs
/// 3. The adapters will be auto-generated as:
///    - UserModelAdapter (typeId: 0)
///    - JobModelAdapter (typeId: 1)
///    - StepModelAdapter (typeId: 2)
///    - PhotoModelAdapter (typeId: 3)
///    - SyncOperationAdapter (typeId: 4)

// Note: These adapters are generated and included in the models file imports
// See generated files:
// - features/auth/data/models/user_model.g.dart
// - features/jobs/data/models/job_model.g.dart
// - core/sync/sync_operation.g.dart
