

import 'package:flutter/material.dart';
import '../Serviesdatamodel/servvices_datamodel.dart';
import '../pages/home_cleaning/provider/home_cleaing_provider.dart';

class DummyServicesData {
  static final Map<String, ServiceCategory> categories = {

    // ============================================
    // WOMEN'S SALON
    // ============================================
    'womens_salon': ServiceCategory(
      id: 'womens_salon',
      name: "Women's Salon",
      description: 'Professional salon services for women',
      highlights: ['Professional Services', 'Quality Products', 'Expert Stylists'],
      bannerImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
      bannerDescription: "Women's Salon",
      tabs: ['Bestsellers', 'Combos', 'Hair', 'Hair Removal', 'Nails', 'Henna'],

      tabBanners: {
        'Bestsellers': TabBanner(
          title: 'Iconic Favorites Loved By All',
          description: 'Everyday Picks With Luxury Touch',
          imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
          backgroundColor: Colors.pink.shade50,
        ),
        'Combos': TabBanner(
          title: 'Save with Combos',
          description: 'Value packages for looks and pamper',
          imageUrl: 'https://images.unsplash.com/photo-1617546824469-7dbb3f9bcd77',
          backgroundColor: Colors.purple.shade50,
        ),
        'Hair': TabBanner(
          title: 'Hair Care & Styling',
          description: 'Cuts, color, and treatments',
          imageUrl: 'https://images.unsplash.com/photo-1624482903659-4f3833a2b11d',
          backgroundColor: Colors.blue.shade50,
        ),
        'Nails': TabBanner(
          title: 'Nail Art & Manicure',
          description: 'Salon-quality nails at home',
          imageUrl: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6',
          backgroundColor: Colors.orange.shade50,
        ),
        'Henna': TabBanner(
          title: 'Henna & Traditional Art',
          description: 'Beautiful, traditional henna designs',
          imageUrl: 'https://images.unsplash.com/photo-1506812574058-fc75fa93fead',
          backgroundColor: Colors.red.shade50,
        ),
      },

      services: [
        // BESTSELLERS (6)
        Service(
          id: 'classic_mani_pedi',
          name: 'Classic Mani-Pedi Combo',
          description: 'Bestselling mani-pedi combo with premium polish.',
          price: 109,
          originalPrice: 180,
          imageUrl: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6',
          category: 'womens_salon',
          tabCategory: 'Bestsellers',
          maxQuantity: 3,
        ),
        Service(
          id: 'back_facial_massage',
          name: 'Back Facial & Massage',
          description: "Cleanse, exfoliate & massage for a glowing back.",
          price: 219,
          originalPrice: 440,
          imageUrl: 'https://images.unsplash.com/photo-1603398938378-dbb65d2e3f93',
          category: 'womens_salon',
          tabCategory: 'Bestsellers',
          maxQuantity: 2,
        ),
        Service(
          id: 'deluxe_facial',
          name: 'Deluxe Radiance Facial',
          description: 'Brightening facial with peel and mask.',
          price: 249,
          originalPrice: 350,
          imageUrl: 'https://images.unsplash.com/photo-1595433562696-19b27f8b1b9a',
          category: 'womens_salon',
          tabCategory: 'Bestsellers',
          maxQuantity: 2,
        ),
        Service(
          id: 'express_glow',
          name: 'Express Glow Facial (30 mins)',
          description: 'Quick glow for busy schedules.',
          price: 129,
          originalPrice: 199,
          imageUrl: 'https://images.unsplash.com/photo-1588776814546-ec04b0d1d808',
          category: 'womens_salon',
          tabCategory: 'Bestsellers',
          maxQuantity: 4,
        ),
        Service(
          id: 'classic_trim_blowdry',
          name: 'Trim & Blowdry',
          description: 'Precision trim with professional blowdry finish.',
          price: 119,
          originalPrice: 180,
          imageUrl: 'https://images.unsplash.com/photo-1599942696369-3babe1b3cbae',
          category: 'womens_salon',
          tabCategory: 'Bestsellers',
          maxQuantity: 5,
        ),
        Service(
          id: 'gel_mani_pedi',
          name: 'Gel Mani-Pedi',
          description: 'Long-lasting gel manicure and pedicure with high-gloss finish.',
          price: 149,
          originalPrice: 210,
          imageUrl: 'https://images.unsplash.com/photo-1600185365483-26d7b10f3b77',
          category: 'womens_salon',
          tabCategory: 'Bestsellers',
          maxQuantity: 4,
        ),

        // COMBOS (6)
        Service(
          id: 'bridal_trial_combo',
          name: 'Bridal Trial + Hair Trial Combo',
          description: 'Makeup + hair trial for brides to finalize look.',
          price: 399,
          originalPrice: 599,
          imageUrl: 'https://images.unsplash.com/photo-1603376786327-0a4e6a706eb4',
          category: 'womens_salon',
          tabCategory: 'Combos',
        ),
        Service(
          id: 'hair_nail_combo',
          name: 'Hair + Nails Combo',
          description: 'Haircut & styling plus mani-pedi bundled.',
          price: 229,
          originalPrice: 330,
          imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
          category: 'womens_salon',
          tabCategory: 'Combos',
        ),
        Service(
          id: 'spa_nail_combo',
          name: 'Spa Relax + Deluxe Nails',
          description: '60 min massage plus deluxe manicure.',
          price: 349,
          originalPrice: 480,
          imageUrl: 'https://images.unsplash.com/photo-1600180758890-6cc69f58aef7',
          category: 'womens_salon',
          tabCategory: 'Combos',
        ),
        Service(
          id: 'color_treatment_combo',
          name: 'Color + Keratin Combo',
          description: 'Global color plus smoothing keratin treatment.',
          price: 499,
          originalPrice: 699,
          imageUrl: 'https://images.unsplash.com/photo-1624482903659-4f3833a2b11d',
          category: 'womens_salon',
          tabCategory: 'Combos',
        ),
        Service(
          id: 'henna_combo',
          name: 'Henna + Mehndi Design Combo',
          description: 'Traditional henna with modern patterns.',
          price: 159,
          originalPrice: 250,
          imageUrl: 'https://images.unsplash.com/photo-1506812574058-fc75fa93fead',
          category: 'womens_salon',
          tabCategory: 'Combos',
        ),
        Service(
          id: 'express_bridal_prep',
          name: 'Express Bridal Prep',
          description: 'Quick bridal makeup & hair ready within short notice.',
          price: 449,
          originalPrice: 650,
          imageUrl: 'https://images.unsplash.com/photo-1556229174-efd5a16c6e09',
          category: 'womens_salon',
          tabCategory: 'Combos',
        ),

        // HAIR (8)
        Service(
          id: 'hair_coloring_global',
          name: 'Hair Coloring - Global',
          description: 'Full head color with premium dye and treatment.',
          price: 399,
          originalPrice: 520,
          imageUrl: 'https://images.unsplash.com/photo-1582095133179-2988d1a4f9c3',
          category: 'womens_salon',
          tabCategory: 'Hair',
        ),
        Service(
          id: 'hair_highlights',
          name: 'Highlights & Balayage',
          description: 'Trendy highlights with tonal finishing.',
          price: 449,
          originalPrice: 599,
          imageUrl: 'https://images.unsplash.com/photo-1600185365483-26d7b10f3b77',
          category: 'womens_salon',
          tabCategory: 'Hair',
        ),
        Service(
          id: 'hair_keratin',
          name: 'Keratin Smoothing',
          description: 'Smoothing treatment for frizz-free hair for months.',
          price: 549,
          originalPrice: 799,
          imageUrl: 'https://images.unsplash.com/photo-1599351431103-4f7e03d2d6d0',
          category: 'womens_salon',
          tabCategory: 'Hair',
        ),
        Service(
          id: 'hair_olaplex',
          name: 'Olaplex Repair Treatment',
          description: 'Bond repair therapy for damaged hair.',
          price: 229,
          originalPrice: 350,
          imageUrl: 'https://images.unsplash.com/photo-1617546824469-7dbb3f9bcd77',
          category: 'womens_salon',
          tabCategory: 'Hair',
        ),
        Service(
          id: 'hair_cutting_custom',
          name: 'Custom Cut & Style',
          description: 'Precision styling suited to your face shape.',
          price: 159,
          originalPrice: 240,
          imageUrl: 'https://images.unsplash.com/photo-1599942696369-3babe1b3cbae',
          category: 'womens_salon',
          tabCategory: 'Hair',
        ),
        Service(
          id: 'scalp_therapy',
          name: 'Scalp Detox Therapy',
          description: 'Clarifying scalp treatment for healthy growth.',
          price: 179,
          originalPrice: 250,
          imageUrl: 'https://images.unsplash.com/photo-1624482903659-4f3833a2b11d',
          category: 'womens_salon',
          tabCategory: 'Hair',
        ),
        Service(
          id: 'hair_extensions',
          name: 'Clip-in Extensions Install',
          description: 'Professional fitting for natural blend.',
          price: 299,
          originalPrice: 420,
          imageUrl: 'https://images.unsplash.com/photo-1603376786327-0a4e6a706eb4',
          category: 'womens_salon',
          tabCategory: 'Hair',
        ),
        Service(
          id: 'hair_trim_quick',
          name: 'Quick Trim',
          description: 'Cut split ends and freshen style quickly.',
          price: 79,
          originalPrice: 120,
          imageUrl: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72f',
          category: 'womens_salon',
          tabCategory: 'Hair',
        ),

        // HAIR REMOVAL (6)
        Service(
          id: 'wax_full_legs',
          name: 'Full Leg Waxing',
          description: 'Smooth, long-lasting waxing with post-care oils.',
          price: 129,
          originalPrice: 199,
          imageUrl: 'https://images.unsplash.com/photo-1600431521340-491eca880813',
          category: 'womens_salon',
          tabCategory: 'Hair Removal',
        ),
        Service(
          id: 'wax_underarm',
          name: 'Underarm Wax',
          description: 'Gentle underarm waxing for smoothness.',
          price: 39,
          originalPrice: 60,
          imageUrl: 'https://images.unsplash.com/photo-1588776814546-ec04b0d1d808',
          category: 'womens_salon',
          tabCategory: 'Hair Removal',
        ),
        Service(
          id: 'threading_eyebrows',
          name: 'Threading - Eyebrows',
          description: 'Precise eyebrow shaping using threading.',
          price: 29,
          originalPrice: 50,
          imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
          category: 'womens_salon',
          tabCategory: 'Hair Removal',
        ),
        Service(
          id: 'laser_underarm',
          name: 'Laser Hair Removal - Underarms (6 sessions)',
          description: 'Package for long-term hair reduction.',
          price: 499,
          originalPrice: 799,
          imageUrl: 'https://images.unsplash.com/photo-1600180758890-6cc69f58aef7',
          category: 'womens_salon',
          tabCategory: 'Hair Removal',
        ),
        Service(
          id: 'threading_fullface',
          name: 'Threading - Full Face',
          description: 'Clean shaping for full face hair removal.',
          price: 79,
          originalPrice: 119,
          imageUrl: 'https://images.unsplash.com/photo-1595433562696-19b27f8b1b9a',
          category: 'womens_salon',
          tabCategory: 'Hair Removal',
        ),
        Service(
          id: 'leg_sugar',
          name: 'Sugar Waxing - Legs',
          description: 'Natural sugar technique for gentler removal.',
          price: 139,
          originalPrice: 199,
          imageUrl: 'https://images.unsplash.com/photo-1600185365483-26d7b10f3b77',
          category: 'womens_salon',
          tabCategory: 'Hair Removal',
        ),

        // NAILS (6)
        Service(
          id: 'mani_classic',
          name: 'Classic Manicure',
          description: 'Hand soak, cuticle care and polish.',
          price: 59,
          originalPrice: 90,
          imageUrl: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6',
          category: 'womens_salon',
          tabCategory: 'Nails',
        ),
        Service(
          id: 'pedi_classic',
          name: 'Classic Pedicure',
          description: 'Foot soak, scrub and polish.',
          price: 69,
          originalPrice: 100,
          imageUrl: 'https://images.unsplash.com/photo-1600185365483-26d7b10f3b77',
          category: 'womens_salon',
          tabCategory: 'Nails',
        ),
        Service(
          id: 'nail_art_premium',
          name: 'Premium Nail Art',
          description: 'Hand-painted nail art for special occasions.',
          price: 99,
          originalPrice: 140,
          imageUrl: 'https://images.unsplash.com/photo-1544213456-b079b4b2d8f8',
          category: 'womens_salon',
          tabCategory: 'Nails',
        ),
        Service(
          id: 'gel_polish',
          name: 'Gel Polish Change',
          description: 'Remove old polish & apply new gel polish.',
          price: 79,
          originalPrice: 110,
          imageUrl: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6',
          category: 'womens_salon',
          tabCategory: 'Nails',
        ),
        Service(
          id: 'acrylic_fullset',
          name: 'Acrylic Full Set',
          description: 'Full set with shaping and finishing.',
          price: 149,
          originalPrice: 220,
          imageUrl: 'https://images.unsplash.com/photo-1544213456-b079b4b2d8f8',
          category: 'womens_salon',
          tabCategory: 'Nails',
        ),
        Service(
          id: 'paraffin_treatment',
          name: 'Paraffin Hand Treatment',
          description: 'Hydrating wax therapy for soft hands.',
          price: 49,
          originalPrice: 80,
          imageUrl: 'https://images.unsplash.com/photo-1544213456-b079b4b2d8f8',
          category: 'womens_salon',
          tabCategory: 'Nails',
        ),

        // HENNA (4)
        Service(
          id: 'bridal_henna',
          name: 'Bridal Henna Full Design',
          description: 'Intricate full-hand bridal henna.',
          price: 299,
          originalPrice: 450,
          imageUrl: 'https://images.unsplash.com/photo-1506812574058-fc75fa93fead',
          category: 'womens_salon',
          tabCategory: 'Henna',
        ),
        Service(
          id: 'party_henna',
          name: 'Party Henna Design',
          description: 'Medium complexity design for events.',
          price: 99,
          originalPrice: 150,
          imageUrl: 'https://images.unsplash.com/photo-1506812574058-fc75fa93fead',
          category: 'womens_salon',
          tabCategory: 'Henna',
        ),
        Service(
          id: 'simple_henna',
          name: 'Simple Henna - Small Area',
          description: 'Quick small henna designs for wrists/ankles.',
          price: 49,
          originalPrice: 80,
          imageUrl: 'https://images.unsplash.com/photo-1506812574058-fc75fa93fead',
          category: 'womens_salon',
          tabCategory: 'Henna',
        ),
        Service(
          id: 'henna_combo_mehndi',
          name: 'Mehndi + Hair Combo',
          description: 'Mehndi design plus hair styling package.',
          price: 399,
          originalPrice: 550,
          imageUrl: 'https://images.unsplash.com/photo-1603376786327-0a4e6a706eb4',
          category: 'womens_salon',
          tabCategory: 'Henna',
        ),
      ],

      // ✅ ADD-ONS FOR WOMEN'S SALON
      addOns: [
        AddOnService(
          title: "Hair Spa Treatment",
          description: "Deep conditioning\ntreatment for hair.",
          price: 99,
          originalPrice: 150,
          image: "hair_spa",
        ),
        AddOnService(
          title: "Nail Art",
          description: "Beautiful designs\non your nails.",
          price: 49,
          originalPrice: 80,
          image: "nail_art",
        ),
        AddOnService(
          title: "Threading (Eyebrows)",
          description: "Perfect eyebrow\nshaping.",
          price: 29,
          originalPrice: 50,
          image: "threading",
        ),
        AddOnService(
          title: "Head Massage",
          description: "Relaxing scalp\nmassage therapy.",
          price: 59,
          originalPrice: 90,
          image: "head_massage",
        ),
        AddOnService(
          title: "Keratin Sample",
          description: "Mini keratin treatment trial.",
          price: 129,
          originalPrice: 200,
          image: "keratin_trial",
        ),
      ],
    ),

    // ============================================
    // WOMEN'S SPA
    // ============================================
    'womens_spa': ServiceCategory(
      id: 'womens_spa',
      name: "Women's Spa",
      description: 'Relaxing spa services for women',
      highlights: ['Relaxation', 'Rejuvenation', 'Professional Care'],
      bannerImage: 'https://images.unsplash.com/photo-1600180758890-6cc69f58aef7',
      bannerDescription: "Women's Spa",
      tabs: ['Relaxation', 'Deep Tissue', 'Couples', 'Ayurvedi'],

      tabBanners: {
        'Relaxation': TabBanner(
          title: 'Pure Relaxation',
          description: 'Unwind with soothing massages',
          imageUrl: 'https://images.unsplash.com/photo-1600180758890-6cc69f58aef7',
          backgroundColor: Colors.green.shade50,
        ),
        'Deep Tissue': TabBanner(
          title: 'Deep Tissue Therapy',
          description: 'Intensive muscle relief',
          imageUrl: 'https://images.unsplash.com/photo-1599058917212-d750089bc07d',
          backgroundColor: Colors.red.shade50,
        ),
      },

      services: [
        Service(
          id: 'relaxation_60',
          name: 'Relaxation Massage - 60 mins',
          description: 'Relax with a soothing massage.',
          price: 329,
          originalPrice: 500,
          imageUrl: 'https://images.unsplash.com/photo-1601979031925-424e53b6caaa',
          category: 'womens_spa',
          tabCategory: 'Relaxation',
          maxQuantity: 1,
        ),
        Service(
          id: 'deep_tissue_90',
          name: 'Deep Tissue Massage - 90 mins',
          description: 'Intense therapy for muscle knots and chronic tension.',
          price: 449,
          originalPrice: 650,
          imageUrl: 'https://images.unsplash.com/photo-1599058917212-d750089bc07d',
          category: 'womens_spa',
          tabCategory: 'Deep Tissue',
        ),
        Service(
          id: 'hot_stone_60',
          name: 'Hot Stone Therapy - 60 mins',
          description: 'Warm stones to melt away tension.',
          price: 399,
          originalPrice: 550,
          imageUrl: 'https://images.unsplash.com/photo-1600431521340-491eca880813',
          category: 'womens_spa',
          tabCategory: 'Relaxation',
        ),
        Service(
          id: 'aroma_45',
          name: 'Aromatherapy - 45 mins',
          description: 'Essential oil blend massage for mental calm.',
          price: 249,
          originalPrice: 350,
          imageUrl: 'https://images.unsplash.com/photo-1603398938378-dbb65d2e3f93',
          category: 'womens_spa',
          tabCategory: 'Relaxation',
        ),
        Service(
          id: 'couples_relax_90',
          name: 'Couples Relaxation - 90 mins',
          description: 'Shared spa experience with two therapists.',
          price: 699,
          originalPrice: 920,
          imageUrl: 'https://images.unsplash.com/photo-1600180758890-6cc69f58aef7',
          category: 'womens_spa',
          tabCategory: 'Couples',
          maxQuantity: 1,
        ),
        Service(
          id: 'ayurvedic_detox',
          name: 'Ayurvedic Detox Therapy',
          description: 'Traditional Ayurvedic oils and massage.',
          price: 359,
          originalPrice: 499,
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
          category: 'womens_spa',
          tabCategory: 'Ayurvedi',
        ),
        Service(
          id: 'face_rejuvenation',
          name: 'Face Rejuvenation Therapy',
          description: 'Non-invasive anti-aging face therapy.',
          price: 329,
          originalPrice: 450,
          imageUrl: 'https://images.unsplash.com/photo-1595433562696-19b27f8b1b9a',
          category: 'womens_spa',
          tabCategory: 'Relaxation',
        ),
        Service(
          id: 'leg_therapy',
          name: 'Leg Revive Treatment',
          description: 'Soothing leg massage and scrub.',
          price: 179,
          originalPrice: 240,
          imageUrl: 'https://images.unsplash.com/photo-1602184873330-6de6f9b6a0fa',
          category: 'womens_spa',
          tabCategory: 'Relaxation',
        ),
        Service(
          id: 'lymphatic_drain',
          name: 'Lymphatic Drainage Massage',
          description: 'Helps reduce swelling and improve circulation.',
          price: 299,
          originalPrice: 399,
          imageUrl: 'https://images.unsplash.com/photo-1601979031925-424e53b6caaa',
          category: 'womens_spa',
          tabCategory: 'Deep Tissue',
        ),
      ],

      // ✅ ADD-ONS FOR WOMEN'S SPA
      addOns: [
        AddOnService(
          title: "Aromatherapy",
          description: "Essential oils for\ndeep relaxation.",
          price: 79,
          originalPrice: 120,
          image: "aromatherapy",
        ),
        AddOnService(
          title: "Hot Stone Therapy",
          description: "Warm stones for\nmuscle relief.",
          price: 129,
          originalPrice: 200,
          image: "hot_stone",
        ),
        AddOnService(
          title: "Foot Scrub",
          description: "Exfoliating foot\ntreatment.",
          price: 49,
          originalPrice: 80,
          image: "foot_scrub",
        ),
        AddOnService(
          title: "Face Massage",
          description: "Rejuvenating facial\nmassage.",
          price: 89,
          originalPrice: 130,
          image: "face_massage",
        ),
      ],
    ),

    // ============================================
    // MEN'S SALON
    // ============================================
    'mens_salon': ServiceCategory(
      id: 'mens_salon',
      name: "Men's Salon",
      description: 'Professional grooming for men',
      highlights: ['Expert Grooming', 'Premium Products', 'Quick Service'],
      bannerImage: 'https://images.unsplash.com/photo-1598257006260-9a01c6d31682',
      bannerDescription: "Men's Salon",
      tabs: ['Haircut', 'Beard', 'Styling'],

      tabBanners: {
        'Haircut': TabBanner(
          title: 'Fresh Haircuts',
          description: 'Modern, classic, or trendy — we’ve got you covered.',
          imageUrl: 'https://images.unsplash.com/photo-1599351431103-4f7e03d2d6d0',
          backgroundColor: Colors.grey.shade100,
        ),
        'Beard': TabBanner(
          title: 'Beard Grooming',
          description: 'Perfect beard trimming & shaping',
          imageUrl: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72f',
          backgroundColor: Colors.brown.shade50,
        ),
      },

      services: [
        Service(
          id: 'haircut_basic',
          name: 'Basic Haircut',
          description: 'Professional haircut with styling.',
          price: 99,
          originalPrice: 150,
          imageUrl: 'https://images.unsplash.com/photo-1599351431103-4f7e03d2d6d0',
          category: 'mens_salon',
          tabCategory: 'Haircut',
          maxQuantity: 10,
        ),
        Service(
          id: 'men_beard_trim',
          name: 'Beard Trim & Shape',
          description: 'Precision trimming with oil massage.',
          price: 59,
          originalPrice: 100,
          imageUrl: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72f',
          category: 'mens_salon',
          tabCategory: 'Beard',
        ),
        Service(
          id: 'men_fade_style',
          name: 'Fade & Style',
          description: 'Modern fades and textured styling.',
          price: 119,
          originalPrice: 160,
          imageUrl: 'https://images.unsplash.com/photo-1610993309185-9b81df7efad0',
          category: 'mens_salon',
          tabCategory: 'Haircut',
        ),
        Service(
          id: 'men_head_massage',
          name: 'Head Massage',
          description: 'Relaxing scalp massage and oil therapy.',
          price: 49,
          originalPrice: 80,
          imageUrl: 'https://images.unsplash.com/photo-1588776814546-ec04b0d1d808',
          category: 'mens_salon',
          tabCategory: 'Styling',
        ),
        Service(
          id: 'hair_color_men',
          name: 'Hair Color Touch-up',
          description: 'Subtle color refresh for a natural look.',
          price: 189,
          originalPrice: 250,
          imageUrl: 'https://images.unsplash.com/photo-1610993309185-9b81df7efad0',
          category: 'mens_salon',
          tabCategory: 'Styling',
        ),
        Service(
          id: 'men_shampoo_condition',
          name: 'Shampoo & Condition',
          description: 'Premium wash and scalp treatment.',
          price: 39,
          originalPrice: 60,
          imageUrl: 'https://images.unsplash.com/photo-1600195077078-7c8153b84878',
          category: 'mens_salon',
          tabCategory: 'Haircut',
        ),
      ],

      // ✅ ADD-ONS FOR MEN'S SALON
      addOns: [
        AddOnService(
          title: "Beard Trim & Styling",
          description: "Professional beard\nstyling service.",
          price: 59,
          originalPrice: 90,
          image: "beard_trim",
        ),
        AddOnService(
          title: "Hair Color",
          description: "Premium hair\ncoloring service.",
          price: 199,
          originalPrice: 300,
          image: "hair_color",
        ),
        AddOnService(
          title: "Head Massage",
          description: "Relaxing scalp\nmassage.",
          price: 49,
          originalPrice: 80,
          image: "head_massage",
        ),
        AddOnService(
          title: "Face Cleanup",
          description: "Deep cleansing\nfacial treatment.",
          price: 149,
          originalPrice: 220,
          image: "face_cleanup",
        ),
      ],
    ),

    // ============================================
    // MEN'S SPA
    // ============================================
    'mens_spa': ServiceCategory(
      id: 'mens_spa',
      name: "Men's Spa",
      description: 'Relaxing spa services for men',
      highlights: ['Stress Relief', 'Muscle Therapy', 'Premium Care'],
      bannerImage: 'https://images.unsplash.com/photo-1601979031925-424e53b6caaa',
      bannerDescription: "Men's Spa",
      tabs: ['Relaxation', 'Sports Massage', 'Aromatherapy'],

      tabBanners: {
        'Relaxation': TabBanner(
          title: 'Ultimate Relaxation',
          description: 'De-stress and rejuvenate',
          imageUrl: 'https://images.unsplash.com/photo-1601979031925-424e53b6caaa',
          backgroundColor: Colors.blue.shade50,
        ),
      },

      services: [
        Service(
          id: 'mens_relaxation',
          name: 'Relaxation Massage - 60 mins',
          description: 'Full body relaxation massage.',
          price: 299,
          originalPrice: 450,
          imageUrl: 'https://images.unsplash.com/photo-1601979031925-424e53b6caaa',
          category: 'mens_spa',
          tabCategory: 'Relaxation',
          maxQuantity: 5,
        ),
        Service(
          id: 'sports_massage',
          name: 'Sports Recovery Massage',
          description: 'Therapeutic massage targeting muscle recovery.',
          price: 349,
          originalPrice: 500,
          imageUrl: 'https://images.unsplash.com/photo-1556229174-efd5a16c6e09',
          category: 'mens_spa',
          tabCategory: 'Sports Massage',
        ),
        Service(
          id: 'cbd_massage',
          name: 'CBD Oil Massage',
          description: 'Relaxing massage with CBD-infused oils.',
          price: 399,
          originalPrice: 550,
          imageUrl: 'https://images.unsplash.com/photo-1599058927742-1cb98c1b8103',
          category: 'mens_spa',
          tabCategory: 'Aromatherapy',
        ),
        Service(
          id: 'steam_sauna',
          name: 'Steam & Sauna Session',
          description: 'Detox and relaxation with steam therapy.',
          price: 179,
          originalPrice: 240,
          imageUrl: 'https://images.unsplash.com/photo-1574634534897-ef1a9f5b2f5d',
          category: 'mens_spa',
          tabCategory: 'Relaxation',
        ),
        Service(
          id: 'deep_tissue_addon',
          name: 'Extra Deep Tissue Add-on',
          description: 'Add-on to increase pressure & duration.',
          price: 99,
          originalPrice: 150,
          imageUrl: 'https://images.unsplash.com/photo-1599058917212-d750089bc07d',
          category: 'mens_spa',
          tabCategory: 'Sports Massage',
        ),
      ],

      // ✅ ADD-ONS FOR MEN'S SPA
      addOns: [
        AddOnService(
          title: "Deep Tissue Add-on",
          description: "Extra pressure for\ndeep relief.",
          price: 99,
          originalPrice: 150,
          image: "deep_tissue",
        ),
        AddOnService(
          title: "Sports Recovery",
          description: "Post-workout muscle\nrecovery therapy.",
          price: 179,
          originalPrice: 250,
          image: "sports_recovery",
        ),
        AddOnService(
          title: "CBD Oil Massage",
          description: "Therapeutic CBD\ninfused massage.",
          price: 249,
          originalPrice: 350,
          image: "cbd_massage",
        ),
      ],
    ),

    // ============================================
    // FURNITURE CLEANING
    // ============================================
    'furniture_cleaning': ServiceCategory(
      id: 'furniture_cleaning',
      name: 'Furniture Cleaning',
      description: 'Professional furniture cleaning services',
      highlights: ['Deep Clean', 'Safe Products', 'Quick Dry'],
      bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
      bannerDescription: 'Furniture Cleaning',
      tabs: ['Sofa', 'Mattress', 'Carpet', 'Curtains', 'Combos'],

      tabBanners: {
        'Sofa': TabBanner(
          title: 'Deep Sofa Cleaning',
          description: 'Professional deep clean for all sofas',
          imageUrl: 'https://images.unsplash.com/photo-1623002117110-7a2fcb48eec2',
          backgroundColor: Colors.cyan.shade50,
        ),
        'Mattress': TabBanner(
          title: 'Mattress Hygiene',
          description: 'Sanitize and refresh your mattress',
          imageUrl: 'https://images.unsplash.com/photo-1600377927703-b8cae9e6b0b7',
          backgroundColor: Colors.indigo.shade50,
        ),
        'Carpet': TabBanner(
          title: 'Carpet Care',
          description: 'Shampoo and restore carpets',
          imageUrl: 'https://images.unsplash.com/photo-1623002117664-78a931bcd1c5',
          backgroundColor: Colors.brown.shade50,
        ),
      },

      services: [
        Service(
          id: 'sofa_cleaning_2seater',
          name: 'Sofa Cleaning - 2 Seater',
          description: 'Deep extraction clean for 2-seater sofas.',
          price: 199,
          originalPrice: 350,
          imageUrl: 'https://images.unsplash.com/photo-1623002117110-7a2fcb48eec2',
          category: 'furniture_cleaning',
          tabCategory: 'Sofa',
          maxQuantity: 20,
        ),
        Service(
          id: 'sofa_cleaning_leather',
          name: 'Leather Sofa Conditioning',
          description: 'Clean, condition and restore leather sofas.',
          price: 249,
          originalPrice: 350,
          imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
          category: 'furniture_cleaning',
          tabCategory: 'Sofa',
        ),
        Service(
          id: 'mattress_king_steam',
          name: 'King Mattress Steam Sanitization',
          description: 'Steam clean to remove mites & odors.',
          price: 179,
          originalPrice: 229,
          imageUrl: 'https://images.unsplash.com/photo-1600377927703-b8cae9e6b0b7',
          category: 'furniture_cleaning',
          tabCategory: 'Mattress',
        ),
        Service(
          id: 'mattress_double_shampoo',
          name: 'Double Mattress Shampoo',
          description: 'Foam shampoo & deodorization.',
          price: 159,
          originalPrice: 199,
          imageUrl: 'https://images.unsplash.com/photo-1588776814612-382e4ab1accc',
          category: 'furniture_cleaning',
          tabCategory: 'Mattress',
        ),
        Service(
          id: 'carpet_full_room',
          name: 'Wall-to-Wall Carpet Cleaning',
          description: 'Deep shampoo and extraction for full-room carpets.',
          price: 229,
          originalPrice: 279,
          imageUrl: 'https://images.unsplash.com/photo-1623002117664-78a931bcd1c5',
          category: 'furniture_cleaning',
          tabCategory: 'Carpet',
        ),
        Service(
          id: 'curtain_onsite',
          name: 'On-site Curtain Steam Cleaning',
          description: 'Steam clean curtains without removal.',
          price: 149,
          originalPrice: 199,
          imageUrl: 'https://images.unsplash.com/photo-1600585154516-8cf07c3b04fb',
          category: 'furniture_cleaning',
          tabCategory: 'Curtains',
        ),
        Service(
          id: 'combo_sofa_mattress',
          name: 'Sofa + Mattress Combo',
          description: 'Discounted bundle for sofa + mattress cleaning.',
          price: 329,
          originalPrice: 399,
          imageUrl: 'https://images.unsplash.com/photo-1616628188869-21e8c0a52d2c',
          category: 'furniture_cleaning',
          tabCategory: 'Combos',
        ),
        Service(
          id: 'upholstery_spot',
          name: 'Upholstery Spot Cleaning',
          description: 'Targeted stain removal for upholstery.',
          price: 89,
          originalPrice: 140,
          imageUrl: 'https://images.unsplash.com/photo-1600607687644-c90b9afc7d1d',
          category: 'furniture_cleaning',
          tabCategory: 'Sofa',
        ),
        Service(
          id: 'velvet_sofa_clean',
          name: 'Velvet Sofa Gentle Clean',
          description: 'Preserve delicate velvet fibers with gentle technique.',
          price: 189,
          originalPrice: 239,
          imageUrl: 'https://images.unsplash.com/photo-1598300056483-90b054d9443f',
          category: 'furniture_cleaning',
          tabCategory: 'Sofa',
        ),
      ],

      // ✅ ADD-ONS FOR FURNITURE CLEANING
      addOns: [
        AddOnService(
          title: "Stain Protection",
          description: "Protective coating\nfor fabric.",
          price: 79,
          originalPrice: 120,
          image: "stain_protection",
        ),
        AddOnService(
          title: "Odor Removal",
          description: "Deep deodorizing\ntreatment.",
          price: 99,
          originalPrice: 150,
          image: "odor_removal",
        ),
        AddOnService(
          title: "Leather Conditioning",
          description: "Premium leather\ncare treatment.",
          price: 149,
          originalPrice: 220,
          image: "leather_care",
        ),
        AddOnService(
          title: "Sanitization",
          description: "Anti-bacterial deep\nsanitizing service.",
          price: 129,
          originalPrice: 180,
          image: "sanitization",
        ),
      ],
    ),

    // ============================================
    // AC CLEANING
    // ============================================
    'ac_cleaning': ServiceCategory(
      id: 'ac_cleaning',
      name: 'AC Cleaning',
      description: 'AC cleaning, repair and maintenance services',
      highlights: ['Improved Efficiency', 'Odor Removal', 'Allergen Reduction'],
      bannerImage: 'https://images.unsplash.com/photo-1581093448796-5c46b8e3e7ef',
      bannerDescription: 'AC Cleaning & Maintenance',
      tabs: [
        'AC Repair and Installation',
        'Centralized and Duct AC',
        'Duct and Filter Combos',
        'Coil Combos',
        'Duct, Filter & Coil Combos',
        'Split AC Cleaning'
      ],

      tabBanners: {
        'AC Repair and Installation': TabBanner(
          title: 'Install & Repair',
          description: 'Expert installation and repair',
          imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97',
          backgroundColor: Colors.blue.shade50,
        ),
        'Split AC Cleaning': TabBanner(
          title: 'Split AC Special',
          description: 'Indoor & outdoor unit servicing',
          imageUrl: 'https://images.unsplash.com/photo-1603791440384-56cd371ee9a7',
          backgroundColor: Colors.grey.shade100,
        ),
      },

      services: [
        // AC Repair & Installation (7)
        Service(
          id: 'split_install_basic',
          name: 'Split AC Installation (Standard)',
          description: 'Professional installation for wall-mounted split AC (standard mount).',
          price: 199,
          originalPrice: 259,
          imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97',
          category: 'ac_cleaning',
          tabCategory: 'AC Repair and Installation',
        ),
        Service(
          id: 'ac_gas_refill',
          name: 'AC Gas Refill (R32/R410)',
          description: 'Refrigerant top-up with leak check.',
          price: 129,
          originalPrice: 179,
          imageUrl: 'https://images.unsplash.com/photo-1581090467410-4d7a5d7e83d2',
          category: 'ac_cleaning',
          tabCategory: 'AC Repair and Installation',
        ),
        Service(
          id: 'comp_repair',
          name: 'Compressor Repair & Replacement',
          description: 'Diagnose and replace faulty compressor parts.',
          price: 499,
          originalPrice: 699,
          imageUrl: 'https://images.unsplash.com/photo-1603791440384-56cd371ee9a7',
          category: 'ac_cleaning',
          tabCategory: 'AC Repair and Installation',
        ),
        Service(
          id: 'window_reinstall',
          name: 'Window AC Re-installation',
          description: 'Safe removal and re-install for window AC units.',
          price: 149,
          originalPrice: 199,
          imageUrl: 'https://images.unsplash.com/photo-1581093588401-52a24f9aeb3a',
          category: 'ac_cleaning',
          tabCategory: 'AC Repair and Installation',
        ),
        Service(
          id: 'ac_electrical_fix',
          name: 'AC Electrical & PCB Repair',
          description: 'Repair of AC electrical faults and control PCB.',
          price: 279,
          originalPrice: 399,
          imageUrl: 'https://images.unsplash.com/photo-1620912189861-b8bdbcf1d779',
          category: 'ac_cleaning',
          tabCategory: 'AC Repair and Installation',
        ),
        Service(
          id: 'ac_mount_upgrade',
          name: 'Heavy Mount Installation',
          description: 'Installation for heavy/large AC models with strong mounting brackets.',
          price: 279,
          originalPrice: 359,
          imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97',
          category: 'ac_cleaning',
          tabCategory: 'AC Repair and Installation',
        ),
        Service(
          id: 'ac_warranty_check',
          name: 'Warranty & Service Check',
          description: 'Pre-sale/pre-warranty inspection and report.',
          price: 99,
          originalPrice: 150,
          imageUrl: 'https://images.unsplash.com/photo-1620912189861-b8bdbcf1d779',
          category: 'ac_cleaning',
          tabCategory: 'AC Repair and Installation',
        ),

        // Centralized & Duct AC (6)
        Service(
          id: 'central_inspect',
          name: 'Centralized AC Inspection',
          description: 'System-level health check for centralized systems.',
          price: 249,
          originalPrice: 299,
          imageUrl: 'https://images.unsplash.com/photo-1597007065565-999c8d14e4c1',
          category: 'ac_cleaning',
          tabCategory: 'Centralized and Duct AC',
        ),
        Service(
          id: 'hvac_duct_clean',
          name: 'HVAC Duct Cleaning',
          description: 'High-power vacuuming to remove dust & mold from ducts.',
          price: 349,
          originalPrice: 449,
          imageUrl: 'https://images.unsplash.com/photo-1581093448841-79887c1e67d6',
          category: 'ac_cleaning',
          tabCategory: 'Centralized and Duct AC',
        ),
        Service(
          id: 'airflow_balance',
          name: 'Airflow Balancing Service',
          description: 'Optimize duct dampers and vents for uniform cooling.',
          price: 199,
          originalPrice: 259,
          imageUrl: 'https://images.unsplash.com/photo-1616627986394-9a2d8792f26a',
          category: 'ac_cleaning',
          tabCategory: 'Centralized and Duct AC',
        ),
        Service(
          id: 'filter_replace',
          name: 'Commercial Filter Replacement',
          description: 'High-efficiency filter install for centralized systems.',
          price: 399,
          originalPrice: 499,
          imageUrl: 'https://images.unsplash.com/photo-1581093448796-5c46b8e3e7ef',
          category: 'ac_cleaning',
          tabCategory: 'Centralized and Duct AC',
        ),
        Service(
          id: 'duct_sealing',
          name: 'Duct Sealing & Insulation',
          description: 'Seal leaks and insulate to reduce energy loss.',
          price: 299,
          originalPrice: 379,
          imageUrl: 'https://images.unsplash.com/photo-1603791440384-56cd371ee9a7',
          category: 'ac_cleaning',
          tabCategory: 'Centralized and Duct AC',
        ),
        Service(
          id: 'hvac_sanitization',
          name: 'HVAC System Sanitization',
          description: 'Anti-microbial sanitization for HVAC systems.',
          price: 429,
          originalPrice: 549,
          imageUrl: 'https://images.unsplash.com/photo-1616627986394-9a2d8792f26a',
          category: 'ac_cleaning',
          tabCategory: 'Centralized and Duct AC',
        ),

        // Duct & Filter Combos (5)
        Service(
          id: 'duct_filter_combo_basic',
          name: 'Duct + Filter Combo Cleaning',
          description: 'Bundle for ducts and filter sanitization.',
          price: 299,
          originalPrice: 379,
          imageUrl: 'https://images.unsplash.com/photo-1581093588401-52a24f9aeb3a',
          category: 'ac_cleaning',
          tabCategory: 'Duct and Filter Combos',
        ),
        Service(
          id: 'all_in_one_air',
          name: 'All-in-One Air Quality Package',
          description: 'Duct cleaning, new filters, and ozone-free sanitization.',
          price: 349,
          originalPrice: 429,
          imageUrl: 'https://images.unsplash.com/photo-1581093448796-5c46b8e3e7ef',
          category: 'ac_cleaning',
          tabCategory: 'Duct and Filter Combos',
        ),
        Service(
          id: 'filter_vip',
          name: 'HEPA Filter Upgrade & Cleaning',
          description: 'Upgrade to HEPA grade filter and cleaning.',
          price: 399,
          originalPrice: 499,
          imageUrl: 'https://images.unsplash.com/photo-1581579186983-9b1acbcad7e3',
          category: 'ac_cleaning',
          tabCategory: 'Duct and Filter Combos',
        ),
        Service(
          id: 'filter_substitute',
          name: 'Filter Replacement (Per Unit)',
          description: 'Replace split AC filter with OEM-equivalent.',
          price: 79,
          originalPrice: 120,
          imageUrl: 'https://images.unsplash.com/photo-1620912189861-b8bdbcf1d779',
          category: 'ac_cleaning',
          tabCategory: 'Duct and Filter Combos',
        ),
        Service(
          id: 'duct_detail_clean',
          name: 'Duct Deep Detail Cleaning',
          description: 'High-pressure detail cleaning for ducts & vents.',
          price: 319,
          originalPrice: 399,
          imageUrl: 'https://images.unsplash.com/photo-1603791440384-56cd371ee9a7',
          category: 'ac_cleaning',
          tabCategory: 'Duct and Filter Combos',
        ),

        // Coil Combos (4)
        Service(
          id: 'evaporator_coil_clean',
          name: 'Evaporator Coil Cleaning',
          description: 'Chemical-free coil cleaning to restore efficiency.',
          price: 189,
          originalPrice: 249,
          imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97',
          category: 'ac_cleaning',
          tabCategory: 'Coil Combos',
        ),
        Service(
          id: 'condenser_coil_clean',
          name: 'Condenser Coil Cleaning',
          description: 'Outdoor coil wash & debris removal.',
          price: 179,
          originalPrice: 229,
          imageUrl: 'https://images.unsplash.com/photo-1616627986394-9a2d8792f26a',
          category: 'ac_cleaning',
          tabCategory: 'Coil Combos',
        ),
        Service(
          id: 'coil_filter_combo',
          name: 'Coil + Filter Combo',
          description: 'Coil flush plus filter sanitization.',
          price: 289,
          originalPrice: 359,
          imageUrl: 'https://images.unsplash.com/photo-1581093448841-79887c1e67d6',
          category: 'ac_cleaning',
          tabCategory: 'Coil Combos',
        ),
        Service(
          id: 'coil_chemical_treat',
          name: 'Chemical Coil Treatment',
          description: 'Safe coil chemical wash for stubborn grime.',
          price: 229,
          originalPrice: 299,
          imageUrl: 'https://images.unsplash.com/photo-1581093588401-52a24f9aeb3a',
          category: 'ac_cleaning',
          tabCategory: 'Coil Combos',
        ),

        // Duct, Filter & Coil Combos (3)
        Service(
          id: 'triple_combo_full',
          name: 'Triple Hygiene Combo',
          description: 'Complete duct + filter + coil deep clean.',
          price: 399,
          originalPrice: 499,
          imageUrl: 'https://images.unsplash.com/photo-1597007065565-999c8d14e4c1',
          category: 'ac_cleaning',
          tabCategory: 'Duct, Filter & Coil Combos',
        ),
        Service(
          id: 'hvac_gold_package',
          name: 'HVAC Gold Package',
          description: 'Premium cleaning with deodorization & follow-up.',
          price: 479,
          originalPrice: 599,
          imageUrl: 'https://images.unsplash.com/photo-1603791440384-56cd371ee9a7',
          category: 'ac_cleaning',
          tabCategory: 'Duct, Filter & Coil Combos',
        ),
        Service(
          id: 'annual_maintenance_plan',
          name: 'Annual Maintenance Plan (4 visits)',
          description: 'Scheduled comprehensive service plan for a year.',
          price: 699,
          originalPrice: 859,
          imageUrl: 'https://images.unsplash.com/photo-1581093588401-52a24f9aeb3a',
          category: 'ac_cleaning',
          tabCategory: 'Duct, Filter & Coil Combos',
        ),

        // Split AC Cleaning (4)
        Service(
          id: 'split_indoor_clean',
          name: 'Split AC Indoor Unit Cleaning',
          description: 'Pressure wash and coil treatment for indoor unit.',
          price: 159,
          originalPrice: 199,
          imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97',
          category: 'ac_cleaning',
          tabCategory: 'Split AC Cleaning',
        ),
        Service(
          id: 'split_outdoor_clean',
          name: 'Split AC Outdoor Unit Cleaning',
          description: 'Clean condenser and fan blades for best performance.',
          price: 179,
          originalPrice: 229,
          imageUrl: 'https://images.unsplash.com/photo-1603791440384-56cd371ee9a7',
          category: 'ac_cleaning',
          tabCategory: 'Split AC Cleaning',
        ),
        Service(
          id: 'split_full_service',
          name: 'Premium Split AC Deep Cleaning',
          description: 'Disassemble and deep clean all components (indoor & outdoor).',
          price: 249,
          originalPrice: 319,
          imageUrl: 'https://images.unsplash.com/photo-1581093448796-5c46b8e3e7ef',
          category: 'ac_cleaning',
          tabCategory: 'Split AC Cleaning',
        ),
      ],

      // ✅ ADD-ONS FOR AC CLEANING
      addOns: [
        AddOnService(
          title: "Anti-bacterial Treatment",
          description: "Kills bacteria in vents and filters.",
          price: 79,
          originalPrice: 120,
          image: "ac_antibacterial",
        ),
        AddOnService(
          title: "Odor Removal",
          description: "Deodorizing treatment to remove smells.",
          price: 99,
          originalPrice: 150,
          image: "ac_deodorize",
        ),
        AddOnService(
          title: "Priority Service",
          description: "Next-day priority scheduling.",
          price: 49,
          originalPrice: 80,
          image: "priority_service",
        ),
      ],
    ),

    // ============================================
    // IV THERAPY
    // ============================================
    'iv_therapy': ServiceCategory(
      id: 'iv_therapy',
      name: 'IV Therapy',
      description: 'Intravenous hydration, immunity and performance drips',
      highlights: ['On-site IVs', 'Medical Supervision', 'Custom Cocktails'],
      bannerImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
      bannerDescription: 'IV Therapy & Wellness',
      tabs: [
        'Bestsellers', 'Express IVs', 'Immunity & Recovery',
        'Fitness & Performance', 'Health & Relief', 'Beauty & Wellness',
        "Couple's Offers", 'Consultation'
      ],

      tabBanners: {
        'Bestsellers': TabBanner(
          title: 'Most Loved Drips',
          description: 'Popular IVs for hydration and recovery',
          imageUrl: 'https://images.unsplash.com/photo-1614200179344-fffa1a6c3b6b',
          backgroundColor: Colors.teal.shade50,
        ),
        'Beauty & Wellness': TabBanner(
          title: 'Glow & Wellness',
          description: 'Skin & anti-aging focused drips',
          imageUrl: 'https://images.unsplash.com/photo-1614200179362-35e3d46f3b1d',
          backgroundColor: Colors.pink.shade50,
        ),
      },

      services: [
        // Bestsellers (6)
        Service(
          id: 'hydration_boost_iv',
          name: 'Hydration Boost IV',
          description: 'Replenish fluids and electrolytes for instant hydration and energy.',
          price: 299,
          originalPrice: 399,
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
          category: 'iv_therapy',
          tabCategory: 'Bestsellers',
        ),
        Service(
          id: 'detox_iv',
          name: 'Detox & Cleanse IV',
          description: 'Flush toxins and rejuvenate your system.',
          price: 349,
          originalPrice: 459,
          imageUrl: 'https://images.unsplash.com/photo-1614200179344-fffa1a6c3b6b',
          category: 'iv_therapy',
          tabCategory: 'Bestsellers',
        ),
        Service(
          id: 'immunity_shield_iv',
          name: 'Immunity Shield IV',
          description: 'Vitamin C + zinc drip for immune support.',
          price: 279,
          originalPrice: 359,
          imageUrl: 'https://images.unsplash.com/photo-1614200179362-35e3d46f3b1d',
          category: 'iv_therapy',
          tabCategory: 'Bestsellers',
        ),
        Service(
          id: 'beauty_glow_iv',
          name: 'Glow & Skin IV',
          description: 'Collagen boost for skin brightness and elasticity.',
          price: 329,
          originalPrice: 429,
          imageUrl: 'https://images.unsplash.com/photo-1614200179362-35e3d46f3b1d',
          category: 'iv_therapy',
          tabCategory: 'Bestsellers',
        ),
        Service(
          id: 'hangover_relief_iv',
          name: 'Hangover Relief IV',
          description: 'Rapid rehydration and detox to recover fast.',
          price: 249,
          originalPrice: 329,
          imageUrl: 'https://images.unsplash.com/photo-1603398938378-c973f9a21a4b',
          category: 'iv_therapy',
          tabCategory: 'Bestsellers',
        ),
        Service(
          id: 'jetlag_recovery_iv',
          name: 'Jet Lag Recovery IV',
          description: 'Restore electrolytes & energy after travel.',
          price: 279,
          originalPrice: 359,
          imageUrl: 'https://images.unsplash.com/photo-1614200179344-fffa1a6c3b6b',
          category: 'iv_therapy',
          tabCategory: 'Bestsellers',
        ),

        // Express IVs (4)
        Service(
          id: 'quick_energy_shot',
          name: 'Quick Energy Shot',
          description: 'Fast B-complex boost (express).',
          price: 199,
          originalPrice: 259,
          imageUrl: 'https://images.unsplash.com/photo-1606811841688-5f1c2e2b35e7',
          category: 'iv_therapy',
          tabCategory: 'Express IVs',
        ),
        Service(
          id: 'immediate_rehydrate',
          name: 'Immediate Rehydrate (30 mins)',
          description: 'Short rehydration drip for instant energy.',
          price: 179,
          originalPrice: 239,
          imageUrl: 'https://images.unsplash.com/photo-1606811841688-5f1c2e2b35e7',
          category: 'iv_therapy',
          tabCategory: 'Express IVs',
        ),
        Service(
          id: 'express_immunity',
          name: 'Express Immunity Boost',
          description: 'Quick vitamin infusion with vitamin C & B12.',
          price: 219,
          originalPrice: 299,
          imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3',
          category: 'iv_therapy',
          tabCategory: 'Express IVs',
        ),
        Service(
          id: 'mini_detox',
          name: 'Mini Detox Express',
          description: 'Short detox flush for immediate refresh.',
          price: 229,
          originalPrice: 299,
          imageUrl: 'https://images.unsplash.com/photo-1614200179344-fffa1a6c3b6b',
          category: 'iv_therapy',
          tabCategory: 'Express IVs',
        ),

        // Immunity & Recovery (5)
        Service(
          id: 'vitc_immunity',
          name: 'Vitamin C Immunity Drip',
          description: 'High-dose vitamin C infusion under medical supervision.',
          price: 299,
          originalPrice: 399,
          imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3',
          category: 'iv_therapy',
          tabCategory: 'Immunity & Recovery',
        ),
        Service(
          id: 'post_illness_recovery',
          name: 'Post-Illness Recovery IV',
          description: 'Rebuild strength and energy after illness.',
          price: 329,
          originalPrice: 449,
          imageUrl: 'https://images.unsplash.com/photo-1614200179344-fffa1a6c3b6b',
          category: 'iv_therapy',
          tabCategory: 'Immunity & Recovery',
        ),
        Service(
          id: 'cold_relief_iv',
          name: 'Cold & Flu Relief IV',
          description: 'Symptom-targeted drip for cold relief.',
          price: 279,
          originalPrice: 359,
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
          category: 'iv_therapy',
          tabCategory: 'Immunity & Recovery',
        ),
        Service(
          id: 'recovery_boost_plus',
          name: 'Recovery Boost Plus',
          description: 'Amino acid + vitamin formula to speed recovery.',
          price: 349,
          originalPrice: 449,
          imageUrl: 'https://images.unsplash.com/photo-1614200179344-fffa1a6c3b6b',
          category: 'iv_therapy',
          tabCategory: 'Immunity & Recovery',
        ),
        Service(
          id: 'detox_plus',
          name: 'Detox Plus IV',
          description: 'Enhanced detox with glutathione & vitamins.',
          price: 369,
          originalPrice: 499,
          imageUrl: 'https://images.unsplash.com/photo-1614200179362-35e3d46f3b1d',
          category: 'iv_therapy',
          tabCategory: 'Immunity & Recovery',
        ),

        // Fitness & Performance (4)
        Service(
          id: 'athlete_recovery_iv',
          name: 'Athlete Recovery IV',
          description: 'Electrolytes + amino acids for post-workout recovery.',
          price: 299,
          originalPrice: 379,
          imageUrl: 'https://images.unsplash.com/photo-1603398938378-c973f9a21a4b',
          category: 'iv_therapy',
          tabCategory: 'Fitness & Performance',
        ),
        Service(
          id: 'pre_competition_boost',
          name: 'Pre-Competition Boost IV',
          description: 'Focus & endurance formula for athletes.',
          price: 319,
          originalPrice: 389,
          imageUrl: 'https://images.unsplash.com/photo-1606811841688-5f1c2e2b35e7',
          category: 'iv_therapy',
          tabCategory: 'Fitness & Performance',
        ),
        Service(
          id: 'post_endurance_repair',
          name: 'Post Endurance Repair IV',
          description: 'Recovery pack with electrolytes and protein precursors.',
          price: 339,
          originalPrice: 419,
          imageUrl: 'https://images.unsplash.com/photo-1614200179344-fffa1a6c3b6b',
          category: 'iv_therapy',
          tabCategory: 'Fitness & Performance',
        ),
        Service(
          id: 'stamina_boost_iv',
          name: 'Stamina Boost IV',
          description: 'B12 + vitamin complex to improve stamina.',
          price: 259,
          originalPrice: 329,
          imageUrl: 'https://images.unsplash.com/photo-1603398938378-c973f9a21a4b',
          category: 'iv_therapy',
          tabCategory: 'Fitness & Performance',
        ),

        // Health & Relief (4)
        Service(
          id: 'migraine_relief_iv',
          name: 'Migraine Relief IV',
          description: 'Hydration and targeted nutrients to ease headaches.',
          price: 269,
          originalPrice: 339,
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
          category: 'iv_therapy',
          tabCategory: 'Health & Relief',
        ),
        Service(
          id: 'allergy_relief_iv',
          name: 'Allergy & Sinus IV',
          description: 'Reduce allergy symptoms with anti-histamine support.',
          price: 299,
          originalPrice: 379,
          imageUrl: 'https://images.unsplash.com/photo-1614200179344-fffa1a6c3b6b',
          category: 'iv_therapy',
          tabCategory: 'Health & Relief',
        ),
        Service(
          id: 'cold_recovery_iv',
          name: 'Cold Recovery IV',
          description: 'Supportive drip for cold symptom relief and recovery.',
          price: 249,
          originalPrice: 329,
          imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3',
          category: 'iv_therapy',
          tabCategory: 'Health & Relief',
        ),
        Service(
          id: 'digestive_relief_iv',
          name: 'Digestive Support IV',
          description: 'Nutrients and enzymes to soothe digestion.',
          price: 239,
          originalPrice: 319,
          imageUrl: 'https://images.unsplash.com/photo-1614200179362-35e3d46f3b1d',
          category: 'iv_therapy',
          tabCategory: 'Health & Relief',
        ),

        // Beauty & Wellness (4)
        Service(
          id: 'anti_aging_iv',
          name: 'Anti-Aging IV',
          description: 'Glutathione and vitamins for antioxidant support.',
          price: 359,
          originalPrice: 469,
          imageUrl: 'https://images.unsplash.com/photo-1614200179362-35e3d46f3b1d',
          category: 'iv_therapy',
          tabCategory: 'Beauty & Wellness',
        ),
        Service(
          id: 'collagen_iv',
          name: 'Collagen Boost IV',
          description: 'Support skin elasticity and hydration.',
          price: 329,
          originalPrice: 429,
          imageUrl: 'https://images.unsplash.com/photo-1614200179362-35e3d46f3b1d',
          category: 'iv_therapy',
          tabCategory: 'Beauty & Wellness',
        ),
        Service(
          id: 'detox_glow_iv',
          name: 'Detox & Glow IV',
          description: 'Glow formula with antioxidants and hydration.',
          price: 349,
          originalPrice: 459,
          imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3',
          category: 'iv_therapy',
          tabCategory: 'Beauty & Wellness',
        ),
        Service(
          id: 'wellness_boost_iv',
          name: 'Wellness IV',
          description: 'General well-being formula for energy & recovery.',
          price: 279,
          originalPrice: 369,
          imageUrl: 'https://images.unsplash.com/photo-1614200179344-fffa1a6c3b6b',
          category: 'iv_therapy',
          tabCategory: 'Beauty & Wellness',
        ),

        // Couple's Offers (2)
        Service(
          id: 'couple_detox_iv',
          name: 'Couple Detox IV',
          description: 'Two-person detox drip in a single booking.',
          price: 549,
          originalPrice: 699,
          imageUrl: 'https://images.unsplash.com/photo-1603398938378-c973f9a21a4b',
          category: 'iv_therapy',
          tabCategory: "Couple's Offers",
        ),
        Service(
          id: 'couple_glow_iv',
          name: 'Couple Glow Therapy',
          description: 'Beauty IV formula for two clients.',
          price: 579,
          originalPrice: 749,
          imageUrl: 'https://images.unsplash.com/photo-1614200179362-35e3d46f3b1d',
          category: 'iv_therapy',
          tabCategory: "Couple's Offers",
        ),

        // Consultation (1)
        Service(
          id: 'iv_doctor_consult',
          name: 'Doctor Consultation for IV Therapy',
          description: 'Medical consultation to determine safe IV formula.',
          price: 129,
          originalPrice: 189,
          imageUrl: 'https://images.unsplash.com/photo-1622227920531-6c9dfc212343',
          category: 'iv_therapy',
          tabCategory: 'Consultation',
          maxQuantity: 1,
        ),
      ],

      // ✅ ADD-ONS FOR IV THERAPY
      addOns: [
        AddOnService(
          title: "Vitamin B12 Booster",
          description: "Quick B12 injection to boost energy.",
          price: 49,
          originalPrice: 80,
          image: "b12_booster",
        ),
        AddOnService(
          title: "Glutathione Shot",
          description: "Antioxidant shot for skin & liver support.",
          price: 99,
          originalPrice: 140,
          image: "glutathione",
        ),
        AddOnService(
          title: "IV Line Charge (Disposable)",
          description: "Disposable IV line & supplies.",
          price: 29,
          originalPrice: 50,
          image: "iv_line",
        ),
      ],
    ),

    // ============================================
    // LAB TESTS
    // ============================================
    'lab_tests': ServiceCategory(
      id: 'lab_tests',
      name: 'Lab Tests',
      description: 'Comprehensive lab tests and health packages',
      highlights: ['Fast Reports', 'Home Sample Collection', 'Accurate Labs'],
      bannerImage: 'https://images.unsplash.com/photo-1581093588401-22e0e3f8f6f0',
      bannerDescription: 'Lab Tests & Health Panels',
      tabs: [
        'Test @ AED 99', 'Popular', 'STD Test', 'Food Intolerance @55%off',
        'Male Health', 'Female Health', 'General Health'
      ],

      tabBanners: {
        'Test @ AED 99': TabBanner(
          title: 'Affordable Screening',
          description: 'Basic tests starting at AED 99',
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
          backgroundColor: Colors.orange.shade50,
        ),
        'Popular': TabBanner(
          title: 'Popular Panels',
          description: 'Frequently booked health packages',
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-4a49b6f5b2cc',
          backgroundColor: Colors.green.shade50,
        ),
      },

      services: [
        // Test @ AED 99 (4)
        Service(
          id: 'basic_health_99',
          name: 'Basic Health Checkup (AED 99)',
          description: 'CBC, Blood Sugar, Cholesterol - quick baseline screening.',
          price: 99,
          originalPrice: 149,
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
          category: 'lab_tests',
          tabCategory: 'Test @ AED 99',
        ),
        Service(
          id: 'lft_99',
          name: 'Liver Function Test (AED 99)',
          description: 'Key liver enzymes to assess hepatic health.',
          price: 99,
          originalPrice: 159,
          imageUrl: 'https://images.unsplash.com/photo-1611691548333-0c4d6f98fdf1',
          category: 'lab_tests',
          tabCategory: 'Test @ AED 99',
        ),
        Service(
          id: 'kft_99',
          name: 'Kidney Function Test (AED 99)',
          description: 'Creatinine, urea and kidney markers.',
          price: 99,
          originalPrice: 159,
          imageUrl: 'https://images.unsplash.com/photo-1579154203451-0b55f1e8c93d',
          category: 'lab_tests',
          tabCategory: 'Test @ AED 99',
        ),
        Service(
          id: 'sugar_panel_99',
          name: 'Glucose Panel (AED 99)',
          description: 'Fasting glucose & HbA1c basic assessment.',
          price: 99,
          originalPrice: 149,
          imageUrl: 'https://images.unsplash.com/photo-1611691548333-0c4d6f98fdf1',
          category: 'lab_tests',
          tabCategory: 'Test @ AED 99',
        ),

        // Popular (6)
        Service(
          id: 'full_body_checkup',
          name: 'Full Body Checkup (80+ parameters)',
          description: 'Comprehensive screening for preventive health.',
          price: 349,
          originalPrice: 499,
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-4a49b6f5b2cc',
          category: 'lab_tests',
          tabCategory: 'Popular',
        ),
        Service(
          id: 'thyroid_profile',
          name: 'Thyroid Profile (T3 T4 TSH)',
          description: 'Complete thyroid hormone panel.',
          price: 149,
          originalPrice: 229,
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-4a49b6f5b2cc',
          category: 'lab_tests',
          tabCategory: 'Popular',
        ),
        Service(
          id: 'diabetes_panel',
          name: 'Diabetes Panel (HbA1c)',
          description: 'Glycemic control and risk assessment.',
          price: 179,
          originalPrice: 249,
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
          category: 'lab_tests',
          tabCategory: 'Popular',
        ),
        Service(
          id: 'lipid_profile',
          name: 'Lipid Profile',
          description: 'Cholesterol, LDL, HDL and triglycerides.',
          price: 129,
          originalPrice: 199,
          imageUrl: 'https://images.unsplash.com/photo-1611691548333-0c4d6f98fdf1',
          category: 'lab_tests',
          tabCategory: 'Popular',
        ),
        Service(
          id: 'vitamin_d_b12',
          name: 'Vitamin D & B12 Panel',
          description: 'Essential vitamin testing for bone & energy.',
          price: 199,
          originalPrice: 299,
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
          category: 'lab_tests',
          tabCategory: 'Popular',
        ),
        Service(
          id: 'cbc',
          name: 'Complete Blood Count (CBC)',
          description: 'Blood cell counts for overall health.',
          price: 89,
          originalPrice: 129,
          imageUrl: 'https://images.unsplash.com/photo-1611691548333-0c4d6f98fdf1',
          category: 'lab_tests',
          tabCategory: 'Popular',
        ),

        // STD Test (3)
        Service(
          id: 'std_comprehensive',
          name: 'Comprehensive STD Panel',
          description: 'HIV, Hep B/C, Syphilis and more - confidential testing.',
          price: 499,
          originalPrice: 649,
          imageUrl: 'https://images.unsplash.com/photo-1606206967928-3e6e61b3b9e9',
          category: 'lab_tests',
          tabCategory: 'STD Test',
        ),
        Service(
          id: 'hiv_test',
          name: 'HIV Antibody Test',
          description: 'Reliable HIV 1 & 2 antibody screening.',
          price: 199,
          originalPrice: 259,
          imageUrl: 'https://images.unsplash.com/photo-1581091870622-7d14f4e8e1c0',
          category: 'lab_tests',
          tabCategory: 'STD Test',
        ),
        Service(
          id: 'hepatitis_panel',
          name: 'Hepatitis B & C Panel',
          description: 'Hepatitis screening for B and C viruses.',
          price: 249,
          originalPrice: 339,
          imageUrl: 'https://images.unsplash.com/photo-1606206967928-3e6e61b3b9e9',
          category: 'lab_tests',
          tabCategory: 'STD Test',
        ),

        // Food Intolerance @55%off (2)
        Service(
          id: 'food_sensitivity_100',
          name: 'Food Sensitivity Test (100 items) - 55% off',
          description: 'Detect intolerances across common foods.',
          price: 499,
          originalPrice: 1099,
          imageUrl: 'https://images.unsplash.com/photo-1600768687618-9ce6f44f6654',
          category: 'lab_tests',
          tabCategory: 'Food Intolerance @55%off',
        ),
        Service(
          id: 'allergy_panel',
          name: 'Allergy Panel (Comprehensive)',
          description: 'Test for pollen, dust, food and more.',
          price: 449,
          originalPrice: 899,
          imageUrl: 'https://images.unsplash.com/photo-1600768687618-9ce6f44f6654',
          category: 'lab_tests',
          tabCategory: 'Food Intolerance @55%off',
        ),

        // Male Health (2)
        Service(
          id: 'male_hormone_test',
          name: 'Male Hormone Panel',
          description: 'Test testosterone, DHEA and related markers.',
          price: 249,
          originalPrice: 329,
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-4a49b6f5b2cc',
          category: 'lab_tests',
          tabCategory: 'Male Health',
        ),
        Service(
          id: 'prostate_psa',
          name: 'PSA - Prostate Health Test',
          description: 'Early detection marker for prostate issues.',
          price: 199,
          originalPrice: 299,
          imageUrl: 'https://images.unsplash.com/photo-1614200179344-fffa1a6c3b6b',
          category: 'lab_tests',
          tabCategory: 'Male Health',
        ),

        // Female Health (3)
        Service(
          id: 'female_hormone_panel',
          name: 'Women\'s Hormone Panel',
          description: 'Estrogen, progesterone and thyroid screening.',
          price: 269,
          originalPrice: 349,
          imageUrl: 'https://images.unsplash.com/photo-1614200179362-35e3d46f3b1d',
          category: 'lab_tests',
          tabCategory: 'Female Health',
        ),
        Service(
          id: 'pcos_profile',
          name: 'PCOS Profile',
          description: 'Comprehensive testing for PCOS diagnosis.',
          price: 299,
          originalPrice: 429,
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
          category: 'lab_tests',
          tabCategory: 'Female Health',
        ),
        Service(
          id: 'fertility_screen',
          name: 'Fertility Screening Package',
          description: 'Hormones, AMH, and relevant fertility markers.',
          price: 399,
          originalPrice: 599,
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-4a49b6f5b2cc',
          category: 'lab_tests',
          tabCategory: 'Female Health',
        ),

        // General Health (3)
        Service(
          id: 'lipid_profile_test',
          name: 'Lipid Profile',
          description: 'Cholesterol & triglyceride measurement.',
          price: 129,
          originalPrice: 199,
          imageUrl: 'https://images.unsplash.com/photo-1611691548333-0c4d6f98fdf1',
          category: 'lab_tests',
          tabCategory: 'General Health',
        ),
        Service(
          id: 'vitamin_levels',
          name: 'Vitamin D & B12 Test',
          description: 'Key vitamins for bone & energy health.',
          price: 199,
          originalPrice: 299,
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
          category: 'lab_tests',
          tabCategory: 'General Health',
        ),
        Service(
          id: 'bmp_panel',
          name: 'Basic Metabolic Panel',
          description: 'Glucose, electrolytes and kidney markers.',
          price: 159,
          originalPrice: 249,
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-4a49b6f5b2cc',
          category: 'lab_tests',
          tabCategory: 'General Health',
        ),
      ],

      // ✅ ADD-ONS FOR LAB TESTS
      addOns: [
        AddOnService(
          title: "Home Sample Collection",
          description: "Technician visits to collect samples.",
          price: 29,
          originalPrice: 50,
          image: "home_collection",
        ),
        AddOnService(
          title: "Priority Report (24 hrs)",
          description: "Get results within 24 hours.",
          price: 49,
          originalPrice: 80,
          image: "priority_report",
        ),
        AddOnService(
          title: "Doctor Tele-Consult",
          description: "Discuss results with a certified doctor.",
          price: 99,
          originalPrice: 150,
          image: "doctor_consult",
        ),
      ],
    ),

    // ============================================
    // DEEP CLEANING
    // ============================================
    'deep_cleaning': ServiceCategory(
      id: 'deep_cleaning',
      name: 'Deep Cleaning',
      description: 'Professional deep cleaning for apartments and villas',
      highlights: ['Thorough', 'Sanitization', 'Quality Team'],
      bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
      bannerDescription: 'Deep Cleaning Services',
      tabs: ['Unfurnished Apartment', 'Furnished Apartment', 'Unfurnished Villa', 'Furnished Villa'],

      tabBanners: {
        'Unfurnished Apartment': TabBanner(
          title: 'Unfurnished',
          description: 'Perfect scrub before move-in',
          imageUrl: 'https://images.unsplash.com/photo-1616628188511-31bce1f9819b',
          backgroundColor: Colors.blueGrey.shade50,
        ),
        'Furnished Villa': TabBanner(
          title: 'Villa Care',
          description: 'Deep clean for furnished villas',
          imageUrl: 'https://images.unsplash.com/photo-1595514534475-1dcb3d706b57',
          backgroundColor: Colors.brown.shade50,
        ),
      },

      services: [
        // Unfurnished Apartment (6)
        Service(
          id: 'studio_unfurnished',
          name: 'Studio Apartment Deep Clean',
          description: 'Walls, floors, bathrooms and kitchen deep clean.',
          price: 249,
          originalPrice: 349,
          imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
          category: 'deep_cleaning',
          tabCategory: 'Unfurnished Apartment',
        ),
        Service(
          id: '1bhk_unfurnished',
          name: '1BHK Unfurnished Deep Clean',
          description: 'Complete cleaning for 1BHK unfurnished units.',
          price: 349,
          originalPrice: 459,
          imageUrl: 'https://images.unsplash.com/photo-1616628188511-31bce1f9819b',
          category: 'deep_cleaning',
          tabCategory: 'Unfurnished Apartment',
        ),
        Service(
          id: '2bhk_unfurnished',
          name: '2BHK Unfurnished Deep Clean',
          description: 'Large space cleaning including balconies and common areas.',
          price: 459,
          originalPrice: 599,
          imageUrl: 'https://images.unsplash.com/photo-1616628188511-31bce1f9819b',
          category: 'deep_cleaning',
          tabCategory: 'Unfurnished Apartment',
        ),
        Service(
          id: '3bhk_unfurnished',
          name: '3BHK Unfurnished Deep Clean',
          description: 'Full deep clean for mid-size apartments.',
          price: 599,
          originalPrice: 799,
          imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a',
          category: 'deep_cleaning',
          tabCategory: 'Unfurnished Apartment',
        ),
        Service(
          id: 'balcony_terrace_clean',
          name: 'Balcony & Terrace Clean',
          description: 'Sweep, pressure wash, and debris removal.',
          price: 99,
          originalPrice: 149,
          imageUrl: 'https://images.unsplash.com/photo-1598300051094-9a5989b7a3a2',
          category: 'deep_cleaning',
          tabCategory: 'Unfurnished Apartment',
        ),
        Service(
          id: 'kitchen_deep_scrub',
          name: 'Kitchen Deep Scrub',
          description: 'Degrease and sanitize kitchen surfaces & appliances.',
          price: 149,
          originalPrice: 220,
          imageUrl: 'https://images.unsplash.com/photo-1598300051094-9a5989b7a3a2',
          category: 'deep_cleaning',
          tabCategory: 'Unfurnished Apartment',
        ),

        // Furnished Apartment (5)
        Service(
          id: '1bhk_furnished_clean',
          name: '1BHK Furnished Deep Clean',
          description: 'Detailed cleaning including furniture & upholstery.',
          price: 399,
          originalPrice: 519,
          imageUrl: 'https://images.unsplash.com/photo-1595514534475-1dcb3d706b57',
          category: 'deep_cleaning',
          tabCategory: 'Furnished Apartment',
        ),
        Service(
          id: '2bhk_furnished_clean',
          name: '2BHK Furnished Deep Clean',
          description: 'Vacuuming, polishing and appliance clean.',
          price: 499,
          originalPrice: 649,
          imageUrl: 'https://images.unsplash.com/photo-1595514534475-1dcb3d706b57',
          category: 'deep_cleaning',
          tabCategory: 'Furnished Apartment',
        ),
        Service(
          id: '3bhk_furnished_clean',
          name: '3BHK Furnished Deep Clean',
          description: 'Comprehensive room-by-room deep clean.',
          price: 649,
          originalPrice: 799,
          imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a',
          category: 'deep_cleaning',
          tabCategory: 'Furnished Apartment',
        ),
        Service(
          id: 'appliance_deep_clean',
          name: 'Appliance Deep Clean',
          description: 'Fridge, oven & small appliance deep sanitization.',
          price: 179,
          originalPrice: 249,
          imageUrl: 'https://images.unsplash.com/photo-1600768687618-9ce6f44f6654',
          category: 'deep_cleaning',
          tabCategory: 'Furnished Apartment',
        ),
        Service(
          id: 'furniture_polish',
          name: 'Furniture Polish & Care',
          description: 'Wood polish & upholstery touch-ups.',
          price: 139,
          originalPrice: 200,
          imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
          category: 'deep_cleaning',
          tabCategory: 'Furnished Apartment',
        ),

        // Unfurnished Villa (3)
        Service(
          id: 'small_villa_unfurnished',
          name: 'Small Villa Deep Clean (Unfurnished)',
          description: 'Comprehensive villa cleaning for empty villas.',
          price: 799,
          originalPrice: 999,
          imageUrl: 'https://images.unsplash.com/photo-1598300051094-9a5989b7a3a2',
          category: 'deep_cleaning',
          tabCategory: 'Unfurnished Villa',
        ),
        Service(
          id: 'large_villa_unfurnished',
          name: 'Large Villa Deep Clean (Unfurnished)',
          description: 'Terrace, pool edge, and full indoor cleaning.',
          price: 1099,
          originalPrice: 1399,
          imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
          category: 'deep_cleaning',
          tabCategory: 'Unfurnished Villa',
        ),
        Service(
          id: 'villa_window_treat',
          name: 'Villa Window & Facade Clean',
          description: 'Exterior window cleaning & minor facade wash.',
          price: 499,
          originalPrice: 699,
          imageUrl: 'https://images.unsplash.com/photo-1595514534475-1dcb3d706b57',
          category: 'deep_cleaning',
          tabCategory: 'Unfurnished Villa',
        ),

        // Furnished Villa (3)
        Service(
          id: 'furnished_small_villa',
          name: 'Furnished Small Villa Deep Clean',
          description: 'Detailed cleaning including upholstery & bedding.',
          price: 899,
          originalPrice: 1149,
          imageUrl: 'https://images.unsplash.com/photo-1616628188511-31bce1f9819b',
          category: 'deep_cleaning',
          tabCategory: 'Furnished Villa',
        ),
        Service(
          id: 'furnished_large_villa',
          name: 'Furnished Large Villa Deep Clean',
          description: 'Luxury-grade deep cleaning with sanitization.',
          price: 1199,
          originalPrice: 1499,
          imageUrl: 'https://images.unsplash.com/photo-1595514534475-1dcb3d706b57',
          category: 'deep_cleaning',
          tabCategory: 'Furnished Villa',
        ),
        Service(
          id: 'villa_premium_sanitize',
          name: 'Premium Villa Sanitization',
          description: 'Post-clean antibacterial mist & surface protection.',
          price: 399,
          originalPrice: 499,
          imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a',
          category: 'deep_cleaning',
          tabCategory: 'Furnished Villa',
        ),
      ],

      // ✅ ADD-ONS FOR DEEP CLEANING
      addOns: [
        AddOnService(
          title: "Extra Room Clean",
          description: "Add an extra room to the package.",
          price: 79,
          originalPrice: 120,
          image: "extra_room",
        ),
        AddOnService(
          title: "Fridge Deep Clean",
          description: "Internal fridge sanitization & deodorize.",
          price: 59,
          originalPrice: 90,
          image: "fridge_clean",
        ),
        AddOnService(
          title: "Oven De-grease",
          description: "Intensive oven cleaning.",
          price: 99,
          originalPrice: 150,
          image: "oven_degrease",
        ),
      ],
    ),

    // ============================================
    // PEST CONTROL
    // ============================================
    'pest_control': ServiceCategory(
      id: 'pest_control',
      name: 'Pest Control',
      description: 'Residential and commercial pest control services',
      highlights: ['Safe Products', 'Follow-up Visits', 'Trained Teams'],
      bannerImage: 'https://images.unsplash.com/photo-1625840982580-7ad59bfc5c51',
      bannerDescription: 'Pest Control & Extermination',
      tabs: ['General', 'Cockroaches', 'Ants', 'Bed Bugs', 'Rodents', 'Mosquitos'],

      tabBanners: {
        'General': TabBanner(
          title: 'Full Home Protection',
          description: 'One-time & maintenance plans',
          imageUrl: 'https://images.unsplash.com/photo-1625840982580-7ad59bfc5c51',
          backgroundColor: Colors.green.shade50,
        ),
      },

      services: [
        // General (4)
        Service(
          id: 'general_full_home',
          name: 'Full Home General Pest Control',
          description: 'Treat common pests across the home – safe & effective.',
          price: 249,
          originalPrice: 329,
          imageUrl: 'https://images.unsplash.com/photo-1625840982580-7ad59bfc5c51',
          category: 'pest_control',
          tabCategory: 'General',
        ),
        Service(
          id: 'kitchen_bath_pest',
          name: 'Kitchen & Bathroom Pest Control',
          description: 'Targeted treatment for moisture-prone areas.',
          price: 149,
          originalPrice: 229,
          imageUrl: 'https://images.unsplash.com/photo-1616628188511-31bce1f9819b',
          category: 'pest_control',
          tabCategory: 'General',
        ),
        Service(
          id: 'quarterly_plan',
          name: 'Quarterly Maintenance Plan (4 visits)',
          description: 'Regular pest control every 3 months.',
          price: 599,
          originalPrice: 749,
          imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
          category: 'pest_control',
          tabCategory: 'General',
        ),
        Service(
          id: 'commercial_roach_control',
          name: 'Commercial Kitchen Pest Control',
          description: 'High-standard treatment for restaurants & kitchens.',
          price: 499,
          originalPrice: 699,
          imageUrl: 'https://images.unsplash.com/photo-1600768687618-9ce6f44f6654',
          category: 'pest_control',
          tabCategory: 'General',
        ),

        // Cockroaches (3)
        Service(
          id: 'cockroach_kitchen',
          name: 'Cockroach Control - Kitchen',
          description: 'Gel & spray combination for kitchen cockroaches.',
          price: 199,
          originalPrice: 299,
          imageUrl: 'https://images.unsplash.com/photo-1600768687618-9ce6f44f6654',
          category: 'pest_control',
          tabCategory: 'Cockroaches',
        ),
        Service(
          id: 'whole_house_roach',
          name: 'Whole House Cockroach Treatment',
          description: 'Full interior & exterior cockroach treatment.',
          price: 279,
          originalPrice: 399,
          imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a',
          category: 'pest_control',
          tabCategory: 'Cockroaches',
        ),
        Service(
          id: 'roach_baiting',
          name: 'Roach Baiting & Monitoring',
          description: 'Strategic bait stations and follow-up inspection.',
          price: 169,
          originalPrice: 240,
          imageUrl: 'https://images.unsplash.com/photo-1595514534475-1dcb3d706b57',
          category: 'pest_control',
          tabCategory: 'Cockroaches',
        ),

        // Ants (3)
        Service(
          id: 'ant_barrier',
          name: 'Ant Barrier Protection',
          description: 'Long-lasting barrier application around entry points.',
          price: 219,
          originalPrice: 329,
          imageUrl: 'https://images.unsplash.com/photo-1598300051094-9a5989b7a3a2',
          category: 'pest_control',
          tabCategory: 'Ants',
        ),
        Service(
          id: 'ant_kitchen_treatment',
          name: 'Ant Control Treatment',
          description: 'Odorless spray & baiting for indoor colonies.',
          price: 169,
          originalPrice: 259,
          imageUrl: 'https://images.unsplash.com/photo-1606811841688-5f1c2e2b35e7',
          category: 'pest_control',
          tabCategory: 'Ants',
        ),
        Service(
          id: 'ant_outdoor',
          name: 'Outdoor Ant Prevention',
          description: 'Perimeter treatment to prevent future invasions.',
          price: 119,
          originalPrice: 179,
          imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a',
          category: 'pest_control',
          tabCategory: 'Ants',
        ),

        // Bed Bugs (3)
        Service(
          id: 'bedbug_single_room',
          name: 'Single Room Bed Bug Treatment',
          description: 'Heat & spray combo for fast eradication.',
          price: 229,
          originalPrice: 349,
          imageUrl: 'https://images.unsplash.com/photo-1625840982580-7ad59bfc5c51',
          category: 'pest_control',
          tabCategory: 'Bed Bugs',
        ),
        Service(
          id: 'bedbug_full_house',
          name: 'Full Home Bed Bug Treatment',
          description: 'Multi-stage treatment with follow-up inspections.',
          price: 399,
          originalPrice: 559,
          imageUrl: 'https://images.unsplash.com/photo-1615461066841-4a49b6f5b2cc',
          category: 'pest_control',
          tabCategory: 'Bed Bugs',
        ),
        Service(
          id: 'bedbug_mattress_pack',
          name: 'Mattress Heat Treatment',
          description: 'Heat treatment specialized for mattresses & bedding.',
          price: 249,
          originalPrice: 349,
          imageUrl: 'https://images.unsplash.com/photo-1606206967928-3e6e61b3b9e9',
          category: 'pest_control',
          tabCategory: 'Bed Bugs',
        ),

        // Rodents (3)
        Service(
          id: 'rodent_kitchen',
          name: 'Rodent Control - Kitchen & Store',
          description: 'Baiting, trapping and sealing entry points.',
          price: 239,
          originalPrice: 329,
          imageUrl: 'https://images.unsplash.com/photo-1600768687618-9ce6f44f6654',
          category: 'pest_control',
          tabCategory: 'Rodents',
        ),
        Service(
          id: 'rodent_full_home',
          name: 'Full Home Rodent Elimination',
          description: 'Integrated rodent management with proofing.',
          price: 359,
          originalPrice: 479,
          imageUrl: 'https://images.unsplash.com/photo-1606206967928-3e6e61b3b9e9',
          category: 'pest_control',
          tabCategory: 'Rodents',
        ),
        Service(
          id: 'rodent_trap_install',
          name: 'Rodent Trap & Monitor Install',
          description: 'Professional trap placement and monitoring.',
          price: 129,
          originalPrice: 199,
          imageUrl: 'https://images.unsplash.com/photo-1625840982580-7ad59bfc5c51',
          category: 'pest_control',
          tabCategory: 'Rodents',
        ),

        // Mosquitos (3)
        Service(
          id: 'mosquito_fogging',
          name: 'Outdoor Mosquito Fogging',
          description: 'Thermal fogging for gardens & patios.',
          price: 199,
          originalPrice: 289,
          imageUrl: 'https://images.unsplash.com/photo-1595514534475-1dcb3d706b57',
          category: 'pest_control',
          tabCategory: 'Mosquitos',
        ),
        Service(
          id: 'mosquito_indoor',
          name: 'Indoor Mosquito Treatment',
          description: 'Odorless indoor misting & prevention treatment.',
          price: 159,
          originalPrice: 249,
          imageUrl: 'https://images.unsplash.com/photo-1616628188511-31bce1f9819b',
          category: 'pest_control',
          tabCategory: 'Mosquitos',
        ),
        Service(
          id: 'mosquito_weekly_plan',
          name: 'Weekly Mosquito Maintenance Plan',
          description: 'Scheduled sprays for long-term protection.',
          price: 499,
          originalPrice: 649,
          imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a',
          category: 'pest_control',
          tabCategory: 'Mosquitos',
        ),
      ],

      // ✅ ADD-ONS FOR PEST CONTROL
      addOns: [
        AddOnService(
          title: "Follow-up Visit",
          description: "Follow-up inspection within 14 days.",
          price: 59,
          originalPrice: 90,
          image: "follow_up",
        ),
        AddOnService(
          title: "Child & Pet Safe Treatment",
          description: "Extra safe chemical protocol for homes with kids/pets.",
          price: 99,
          originalPrice: 140,
          image: "safe_treatment",
        ),
        AddOnService(
          title: "Proofing & Sealing",
          description: "Minor openings sealing for rodent prevention.",
          price: 149,
          originalPrice: 220,
          image: "proofing",
        ),
      ],
    ),

    // ============================================
    // PACKERS & MOVERS
    // ============================================
    'packers_movers': ServiceCategory(
      id: 'packers_movers',
      name: 'Packers and Movers',
      description: 'Professional packing and relocation services',
      highlights: ['Insured Move', 'Fragile Handling', 'Timely Delivery'],
      bannerImage: 'https://images.unsplash.com/photo-1581092795360-8a5e2ab19f62',
      bannerDescription: 'Packers & Movers',
      tabs: ['Apartment', 'Villa', 'Single Items'],

      tabBanners: {
        'Apartment': TabBanner(
          title: 'Apartment Moves',
          description: '1BHK to 3BHK shifting solutions',
          imageUrl: 'https://images.unsplash.com/photo-1616628188511-31bce1f9819b',
          backgroundColor: Colors.blue.shade50,
        ),
      },

      services: [
        // Apartment (3)
        Service(
          id: '1bhk_shifting',
          name: '1BHK Apartment Shifting',
          description: 'Packing & moving for 1BHK including fragile items.',
          price: 799,
          originalPrice: 999,
          imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
          category: 'packers_movers',
          tabCategory: 'Apartment',
        ),
        Service(
          id: '2bhk_shifting',
          name: '2BHK Apartment Shifting',
          description: 'Packing, loading and unloading with secure transit.',
          price: 1099,
          originalPrice: 1399,
          imageUrl: 'https://images.unsplash.com/photo-1616628188511-31bce1f9819b',
          category: 'packers_movers',
          tabCategory: 'Apartment',
        ),
        Service(
          id: '3bhk_shifting',
          name: '3BHK Apartment Shifting',
          description: 'Full relocation with insurance and dedicated crew.',
          price: 1499,
          originalPrice: 1899,
          imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a',
          category: 'packers_movers',
          tabCategory: 'Apartment',
        ),

        // Villa (3)
        Service(
          id: 'small_villa_move',
          name: 'Small Villa Relocation',
          description: 'Packing & moving for small villas including fragile handling.',
          price: 1799,
          originalPrice: 2199,
          imageUrl: 'https://images.unsplash.com/photo-1606811841688-5f1c2e2b35e7',
          category: 'packers_movers',
          tabCategory: 'Villa',
        ),
        Service(
          id: 'luxury_villa_move',
          name: 'Luxury Villa Relocation',
          description: 'Full-service moving with dedicated move manager.',
          price: 2599,
          originalPrice: 3199,
          imageUrl: 'https://images.unsplash.com/photo-1598300051094-9a5989b7a3a2',
          category: 'packers_movers',
          tabCategory: 'Villa',
        ),
        Service(
          id: 'villa_combo_cleaning',
          name: 'Villa Packing + Cleaning Combo',
          description: 'Relocation with pre/post deep cleaning included.',
          price: 2899,
          originalPrice: 3499,
          imageUrl: 'https://images.unsplash.com/photo-1600768687618-9ce6f44f6654',
          category: 'packers_movers',
          tabCategory: 'Villa',
        ),

        // Single Items (3)
        Service(
          id: 'single_furniture_move',
          name: 'Single Furniture Move',
          description: 'Safe packing & transport for single large items.',
          price: 199,
          originalPrice: 289,
          imageUrl: 'https://images.unsplash.com/photo-1581092795360-8a5e2ab19f62',
          category: 'packers_movers',
          tabCategory: 'Single Items',
        ),
        Service(
          id: 'appliance_move',
          name: 'Appliance Move: Fridge/Washer/AC',
          description: 'Cushioning and secure transport for appliances.',
          price: 149,
          originalPrice: 229,
          imageUrl: 'https://images.unsplash.com/photo-1606206967928-3e6e61b3b9e9',
          category: 'packers_movers',
          tabCategory: 'Single Items',
        ),
        Service(
          id: 'fragile_item_delivery',
          name: 'Fragile Item Packing & Delivery',
          description: 'Custom crates & foam wrapping for fragile goods.',
          price: 179,
          originalPrice: 259,
          imageUrl: 'https://images.unsplash.com/photo-1625840982580-7ad59bfc5c51',
          category: 'packers_movers',
          tabCategory: 'Single Items',
        ),
      ],

      // ✅ ADD-ONS FOR PACKERS & MOVERS
      addOns: [
        AddOnService(
          title: "Insurance (Per Move)",
          description: "Declared value insurance for items in transit.",
          price: 99,
          originalPrice: 150,
          image: "move_insurance",
        ),
        AddOnService(
          title: "Fragile Crating",
          description: "Custom wooden crates for delicate items.",
          price: 149,
          originalPrice: 250,
          image: "fragile_crate",
        ),
        AddOnService(
          title: "Expedited Delivery",
          description: "Faster delivery with priority scheduling.",
          price: 199,
          originalPrice: 299,
          image: "expedite_delivery",
        ),
      ],
    ),
  };

  static ServiceCategory? getCategory(String categoryId) {
    return categories[categoryId];
  }
}

